@startuml
' skinparam nodesep 50 CONTROLS node horizontal separation
' skinparam ranksep 60 CONTROLS vertical separation

object Competition
object "Inscription phase" as Inscription {
  Date
  Place
}
object CompetitionDraw
object Batch
object Weighing {
  AthleteBodyWeight
  SnatchOpener
  CleanJerkOpener
}
object ClassificationAct
object CategoryClassification
object SinclairClassification
object SinclairMaloneClassification
object EliteClassification
object EliteSpreadsheetMale
object EliteSpreadsheetFemale
object Platform
object Club
object Athlete
enum Gender {
  MALE
  FEMALE
}
object "Technical officers" as TC
object Judge
object Marshall
object CompetitionSecretary
object TimeJudge
object Lift
enum Type {
  SNATCH
  CLEAN_&_JERK
}
enum LiftStatus {
  PENDING
  VALID
  NULL
  REJECTED
}
enum Countdown {
  60_SECONDS
  120_SECONDS
}
object BarSet
object Bar
object FemaleBar {
  weight: 15kg
  Object[] meassures
}
object MaleBar {
  weight: 20kg
  Object[] meassures
}
object Plates
enum Plate {
  25-RED
  15-YELLOW
  10-GREEN
  5-WHITE
  2.5-RED
  1.5-YELLOW
  1-GREEN
  0.5-WHITE
}
object Collar {
  weight: 2.5kg
}

object Category {
  Gender
}

object Sub15 {
  age: 13-15
}

object Sub17 {
  age: 13-17
}

object Junior {
  age: 13-20
}

object Senior {
  age: 13_Plus
}

object Master {
  age: 35_Plus
}

enum Sub15_M {
  45
  50
  56
  62
  69
  77
  85
  85_PLUS
}

enum Sub15_W {
 44
 48
 53
 58
 63
 69
 75
 75_PLUS
}

enum Sub17_M {
  50
  56
  62
  69
  77
  85
  94
  94_PLUS
}

enum Sub17_W {
 50
 56
 62
 69
 77
 85
 94
 94_PLUS
}

enum Standar_M {
56
62
69
77
85
94
105
+105
}

enum Standar_W {
48
53
58
63
69
75
90
+90
}

Competition *-- Inscription
Inscription *-- Athlete
Athlete <-- Gender
Club *-- Athlete
Competition *-- CompetitionDraw
Competition *-- "1..*" Batch
Competition *-- ClassificationAct
ClassificationAct <|-- CategoryClassification
ClassificationAct <|-- SinclairClassification
ClassificationAct <|-- SinclairMaloneClassification
ClassificationAct <|-- EliteClassification
EliteClassification *-- EliteSpreadsheetMale
EliteClassification *-- EliteSpreadsheetFemale

Batch -right-> "next                                       " ClassificationAct
Inscription -right-> "next" CompetitionDraw
CompetitionDraw -right-> "next" Batch

Batch *-- Weighing
Batch *-- "1..2" Platform
Batch *--- "1..*" Athlete
Batch *--- TC

TC *-- "3..6" Judge
TC *-- CompetitionSecretary
TC *-- "0..1" Marshall
TC *-- "0..1" TimeJudge

Batch *-- "1..*" Lift

Lift *-- Type
Lift *-- LiftStatus
Lift *-- Countdown
Lift o-- BarSet
BarSet *-- Bar
BarSet *-- Plates
BarSet *-- "2" Collar
Bar <|-- FemaleBar
Bar <|-- MaleBar
Plates *-- Plate

Category <|-- Sub15
Category <|-- Sub17
Category <|-- Junior
Category <|-- Senior
Category <|-- Master

Sub15 <-- Sub15_W
Sub15 <-- Sub15_M
Sub17 <-- Sub17_W
Sub17 <-- Sub17_M
Junior <-- Standar_M
Junior <-- Standar_W
Senior <-- Standar_M
Senior <-- Standar_W
Master <-- Standar_M
Master <-- Standar_W


@enduml
