@startuml
state "Pending new lifters to register" as PendingLiftersToRegister
state "Is the registration time still open?" as IsRegistrationOpenCHC <<choice>>
state "More lifters to register pending?" as MoreLiftersToRegisterCHC <<choice>>
state "A new lifter was registered" as NewLifterRegistered
state "Registration time is over" as RegistrationTimeOver
state "Is there any lifter registered?" as AnyLiftersRegisteredCHC <<choice>>
state "Competition order drawn" as CompetitionOrderDrawn
state "Pending new batches" as PendingNewBatch
state "A new category from a\ncertain batch started" as StartedNewBatchCategory
state "More batches pending?" as MoreCategoryBatchesCHC <<choice>>
state "Classification is open" as OpenClassification
state "Classification completed" as CompletedClassification
state "More batches from other categories pending?" as MoreBatchesCHC <<choice>>
state "All batches are completed" as CompletedBatches

[*] --> PendingLiftersToRegister
PendingLiftersToRegister --> IsRegistrationOpenCHC : A new lifter tries\nto be registered
IsRegistrationOpenCHC --> RegistrationTimeOver : Registration time\nran out
IsRegistrationOpenCHC --> NewLifterRegistered : The registration period\nis still open
NewLifterRegistered --> MoreLiftersToRegisterCHC
MoreLiftersToRegisterCHC --> PendingLiftersToRegister : Lifters remain to\nbe registered
MoreLiftersToRegisterCHC --> RegistrationTimeOver : All lifters are\nregistered
PendingLiftersToRegister --> RegistrationTimeOver : Registration time\nran out
RegistrationTimeOver --> AnyLiftersRegisteredCHC
AnyLiftersRegisteredCHC --> CompetitionOrderDrawn : The draw takes place
AnyLiftersRegisteredCHC --> [*] : No lifter has signed up
CompetitionOrderDrawn --> PendingNewBatch : The development of the\ncompetition begins

PendingNewBatch --> StartedNewBatchCategory
StartedNewBatchCategory --> MoreCategoryBatchesCHC : New category for a certain\nbatch is completed

MoreCategoryBatchesCHC --> PendingNewBatch : Some batches from the\nsame category have not\nbeen classified yet
MoreCategoryBatchesCHC --> OpenClassification : All batches from a the same\ncategory are completed
OpenClassification --> CompletedClassification : Score is calculated and\nwinner is determined
CompletedClassification --> MoreBatchesCHC
MoreBatchesCHC --> PendingNewBatch : Some categories have not\nbeen classified yet
MoreBatchesCHC --> CompletedBatches : All batches have been\nclassified
CompletedBatches --> [*]
@enduml
