@startuml

''''''''''''''''''''''''''''''
''
'' STATES AND CHOICES
'' '' ''

state "Bar pending to be charged" as BarPendingToBeCharged
state "Bar charged" as ChargedBar 
state "Next and following lifters are announced" as NextAndFollowingLiftersAnnounced

state "Was there a change in the lift weight?" as ChangeInLiftWeightCHC <<choice>>
state "Does the lifter have any lift weight change attempt?" as AnyChangeAttemptCHC <<choice>>

state "The lifter lift weight change\nattempts decreased by 1" as AttemptsDecreased
state "Does the bar weight remain?" as BarWeightRemainsCHC <<choice>>
state "Does the lifter decide to perform its lift?" as IsLiftGoingToBeRejectedCHC <<choice>>

state "The timer started" as TimerStarted
state "Did the lifter perform its lift?" as WasLiftPerformedCHC <<choice>>
state "Was there a change in the lift weight?" as ChangeInLiftWeightAfterTimerCHC <<choice>>
state "Does the lifter have any lift weight change attempt?" as AnyChangeAttemptAfterTimerCHC <<choice>>

state "The lift was performed" as LiftWasPerformed
state "The timer stopped" as TimerStopped
state "Rejected lift" as RejectedLift

state "Was the lift valid?" as WasLiftValidCHC <<choice>>
state "Valid lift" as ValidLift
state "Null lift" as NullLift

''''''''''''''''''''''''''''''
''
'' TRANSITIONS
''

[*] --> BarPendingToBeCharged

BarPendingToBeCharged --> ChargedBar
ChargedBar --> NextAndFollowingLiftersAnnounced

''
'' When lifters are announced:
''

NextAndFollowingLiftersAnnounced --> ChangeInLiftWeightCHC
ChangeInLiftWeightCHC --> AnyChangeAttemptCHC : The lifter tries to make\na lift weight change
AnyChangeAttemptCHC --> IsLiftGoingToBeRejectedCHC : The lifter has no more attempts\nat lift weight change
AnyChangeAttemptCHC --> AttemptsDecreased : The lifter still has any\nlift weight change attempt

AttemptsDecreased --> BarWeightRemainsCHC
BarWeightRemainsCHC --> ChargedBar : The bar weight remains
BarWeightRemainsCHC --> BarPendingToBeCharged : The bar weight changes

ChangeInLiftWeightCHC --> IsLiftGoingToBeRejectedCHC : The lifter keeps\nits lift weight
IsLiftGoingToBeRejectedCHC --> TimerStarted : The lifter decides to\nperform its lift
IsLiftGoingToBeRejectedCHC --> RejectedLift : The lifter rejected its lift
RejectedLift --> [*]

''
'' When timer started:
''

TimerStarted --> WasLiftPerformedCHC
WasLiftPerformedCHC --> LiftWasPerformed : The lifter performed its lift
WasLiftPerformedCHC --> TimerStopped : The lifter didn't\nperform its lift
WasLiftPerformedCHC --> ChangeInLiftWeightAfterTimerCHC : The lifter tries to make\na lift weight change

ChangeInLiftWeightAfterTimerCHC --> WasLiftPerformedCHC : The timer started more\nthan 30 seconds ago
ChangeInLiftWeightAfterTimerCHC --> AnyChangeAttemptAfterTimerCHC : The timer started less\nthan 30 seconds ago

AnyChangeAttemptAfterTimerCHC --> WasLiftPerformedCHC : The lifter has no more attempts\nat lift weight change
AnyChangeAttemptAfterTimerCHC --> AttemptsDecreased : The lifter still has any\nlift weight change attempt

LiftWasPerformed --> TimerStopped

''
'' When time is over:
''

TimerStopped --> WasLiftValidCHC
WasLiftValidCHC --> ValidLift : The lift was judged\nas valid
WasLiftValidCHC --> NullLift : The lift was judged\nas null

ValidLift --> [*]
NullLift --> [*]

@enduml
