@startuml

'title HalteroCMS

state "COMPETITION_NOT_CREATED" as competitionNotCreated
state "COMPETITION_CREATED" as competitionCreated

state "BATCHES_NOT_CREATED" as batchesNotCreated
state "BATCHES_CREATED" as batchesCreated
state "BATCH_PLAYED" as batchPlayed
state "BATCH_NOT_PLAYED" as batchNotPlayed
state "GENERATE_CLASSIFICATION" as generateClassifications


'[*] --> competitionNotCreated
'competitionNotCreated --> competitionCreated
'competitionCreated --> batchesNotCreated
'batchesNotCreated --> batchesCreated
'batchesCreated --> batchNotPlayed
'batchNotPlayed --> batchPlayed
'batchPlayed --> generateClassifications
'generateClassifications --> [*]


'scale 350 width
'[*] --> NotShooting
'
'state NotShooting {
'  [*] --> Idle
'  Idle --> Configuring : EvConfig
'  Configuring --> Idle : EvConfig
'}
'
'state Configuring {
'  [*] --> NewValueSelection
'  NewValueSelection --> NewValuePreview : EvNewValue
'  NewValuePreview --> NewValueSelection : EvNewValueRejected
'  NewValuePreview --> NewValueSelection : EvNewValueSaved
'
'  state NewValuePreview {
'     State1 -> State2
'  }
'
'}
@enduml