@startuml
state SHOWED_CATEGORIES
state enterCancelCHC <<choice>>
state editCategory {
  state " " as pendingCategory
  state createOrModifyCHC <<choice>>
  state " " as providedCategory
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  [*] --> pendingCategory
  note on link
    System requires:
    * A specific or a 
    new category
  end note
  pendingCategory --> createOrModifyCHC
  createOrModifyCHC --> providedCategory
  note on link
    User provides:
    * A specific category

    System allows to:
    * cancel
  end note
 createOrModifyCHC --> createOrModifyCHC2 : The user is creating\na new category
  providedCategory --> showedData
  note on link
    System shows:
    * Current category data
  end note
  showedData --> createOrModifyCHC2 : The user is modifying\na category
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * The competition type
    * Minimum age (included)
    * Maximum age (included)
    * Gender
    * Bodyweight categories

    System allows to:
    * cancel
  end note
  pendingData -u-> enterCancelCHC
  pendingData --> providedData
  note on link
    User provides:
    * The competition type
    * Minimum age (included)
    * Maximum age (included)
    * Gender
    * Bodyweight categories
  end note
  providedCategory -u-> enterCancelCHC
  providedData --> [*]
  note on link
    System allows to:
    * showCategories
  end note
}
state EDITED_CATEGORY

SHOWED_CATEGORIES -d-> editCategory
note on link
  User requests to:
  * editCategory
end note

editCategory -d-> EDITED_CATEGORY

enterCancelCHC -u-> SHOWED_CATEGORIES
note on link
  User requests to:
  * cancel
end note

footer \n\n\n Especificación del caso de uso "editCategory"
@enduml
