@startuml
state LOGED_IN
state DELETED_CATEGORY
state EDITED_CATEGORY

state enterShowCategoriesCHC <<choice>>

state showCategories {
  [*] --> [*]
  note on link
    System shows:
    * edited categories

    System allows to:
    * deleteCategory
    * editCategory
    * showClubs
    * showOrganizers
    * showInscribers
    * logout
  end note
}
state SHOWED_CATEGORIES

LOGED_IN --> enterShowCategoriesCHC
DELETED_CATEGORY --> enterShowCategoriesCHC
EDITED_CATEGORY --> enterShowCategoriesCHC
enterShowCategoriesCHC --> showCategories
note on link
  User requests to:
  * showCategories
end note
showCategories --> SHOWED_CATEGORIES

footer \n\n\n Especificación del caso de uso "showCategories"
@enduml
