@startuml
left to right direction

package competitionManagement {
 usecase openInscriptionsPeriod
 usecase showInscriptions
 usecase closeInscriptions

 usecase deleteCompetition
 usecase editCompetition
 usecase showCompetitions

 usecase drawLifters
 usecase inscribeLifter
 usecase uninscribeLifter
 usecase showInscribedLifters

 usecase createClassifications
 usecase downloadClassifications
 usecase showClassifications
}

Time --> closeInscriptions
Organizer --> openInscriptionsPeriod
Organizer --> showInscriptions
Organizer --> drawLifters
Organizer --> deleteCompetition
Organizer --> editCompetition
Organizer --> showCompetitions
Organizer --> createClassifications
Organizer --> showClassifications
Organizer --> downloadClassifications

Inscriber --> inscribeLifter
Inscriber --> uninscribeLifter
Inscriber --> showInscribedLifters

footer \n\nFigura 6. Casos de uso relacionados con la competición
@enduml