@startuml

left to right direction

package organizationManagement {
    usecase showClubs
    usecase editClub
    usecase deleteClub
    usecase showOrganizers
    usecase editOrganizer
    usecase deleteOrganizer
    usecase showInscribers
    usecase deleteInscriber
    usecase editInscriber
    usecase deleteCategory
    usecase editCategory
    usecase showCategories
    usecase editBodyWeightCategory
    usecase deleteBodyWeightCategory
}

OrganizationSecretary --> showClubs
OrganizationSecretary --> editClub
OrganizationSecretary --> deleteClub
OrganizationSecretary --> editBodyWeightCategory
OrganizationSecretary --> deleteBodyWeightCategory

OrganizationSecretary --> showOrganizers
OrganizationSecretary --> editOrganizer
OrganizationSecretary --> deleteOrganizer
OrganizationSecretary --> showOrganizers

OrganizationSecretary --> deleteInscriber
OrganizationSecretary --> editInscriber
OrganizationSecretary --> showInscribers

OrganizationSecretary --> deleteCategory
OrganizationSecretary --> editCategory
OrganizationSecretary --> showCategories

footer \n\nFigura 4. Casos de uso relacionados con el actor secretario de competición
@enduml