@startuml
left to right direction

package TimerManagement {
  usecase start
  usecase pause
  usecase resume
  usecase setDuration
  usecase stop
}

TimeKeeper --> start
TimeKeeper --> pause
TimeKeeper --> resume
TimeKeeper --> stop
TimeKeeper --> setDuration
Time --> stop

footer \n\nFigure 8. Casos de uso relacionados con el timer
@enduml