@startuml

object Competition {
   type: CompetitionType
}

class CompetitionType {
  name
}

object "Inscription" as Inscription {
  Date
  Place
}

object CompetitionDraw

object Batch {
  location
  name
  time
}

object Weighing {
  time
  Lifter identification
  LifterBodyWeight
  SnatchOpener
  CleanJerkOpener
}

object ClassificationAct

object CategoryClassification

object SinclairClassification {
  coefficient: SinclairCoefficient
}

object SinclairMaloneClassification {
  coefficient: SinclairMaloneCoefficient
}

object EliteClassification {
  coefficientsMales: [EliteCoefficientMale]
  coefficientsMales: [EliteCoefficientFemale]
}

object Platform {
  name
}
object BarLoaders

object Club

object Lifter {
  name
  birthYear
}

enum Gender {
  MALE(M)
  FEMALE(F)
}



object Judge

object Marshall

object CompetitionSecretary

object Timekeeper

object Lift

enum LiftType {
  SNATCH
  CLEAN_&_JERK
}

enum LiftStatus {
  PENDING
  VALID
  NULL
  REJECTED
}

enum Countdown {
  1_MINUTES(1)
  2_MINUTES(2)
}

object BarSet

enum Bar {
  FEMALE (15kg)
  MALE (20kg)
}

object Plates

enum Plate {
  BIG_RED (25KG)
  BIG_BLUE (20KG)
  BIG_YELLOW (15KG)
  BIG_GREEN (10KG)
  BIG_WHITE (5)
  SMALL_RED (2.5KG)
  SMALL_BLUE (2KG)
  SMALL_YELLOW (1.5KG)
  SMALL_GREEN (1KG)
  SMALL_WHITE (0.5KG)
}

enum Collar {
  COLLAR(2.5KG)
}

object Iteration

object Announcement

object Category {

}

object AgeRange {
  min
  max
}

Category *-- AgeRange

object BodyWeightRange {
  min
  max
}

object "Technical officers" as TC


Competition --> CompetitionType
Competition *-- Inscription
Inscription *-- "1..*" Lifter

Club o-- "1..*" Lifter
Competition *-- CompetitionDraw
Competition *-- "1..*" Batch
Competition *-- ClassificationAct
ClassificationAct <|-- CategoryClassification
ClassificationAct <|-- SinclairClassification
ClassificationAct <|-- SinclairMaloneClassification
ClassificationAct <|-- EliteClassification

Batch "next" --> ClassificationAct
Inscription --> "next" CompetitionDraw
CompetitionDraw --> "next" Batch

Batch *-- Weighing
Batch o-- "1..2" Platform
Batch "1..*" *--  Lifter

Batch *--- TC
TC <|-- "3..6" Judge
TC <|-- CompetitionSecretary
TC <|-- "0..1" Marshall
TC <|-- "0..1" Timekeeper
TC <|-- "1..*" BarLoaders

Platform  *-  "1..*" Iteration
Iteration *-- "1..*"  Announcement

Announcement -- Lifter : next
Announcement -- Lifter : following

Lift *-- LiftType
Lift *-- LiftStatus
Lift *-- Countdown
Lift o-- BarSet

BarSet *-- Bar
BarSet *-- Plates
BarSet *-- "2" Collar
Plates *-- Plate

Lifter o---> Lift
Lifter *--> Gender
Lifter *-- Category
Lifter *-- Category

Category -> Gender
Category o-- "1..*" BodyWeightRange

CompetitionSecretary --> ClassificationAct
CompetitionSecretary --> Announcement
Timekeeper --> Lifter
Marshall --> Lifter
BarLoaders --> BarSet
Judge --> LiftStatus
Judge --> Weighing

footer Figura 1.  Modelo del dominio
@enduml
