@startuml

state " " as launch
state login

[*] --> launch
note on link
  launch
end note

launch --> login

state " " as showCategories
showCategories: <img:./images/1_2_1_4_spectatorBatch.png>

state " " as showClubs


state " " as showOrganizers


state " " as showInscribers

@enduml