@startuml

state "...." as launch
state "Logged as competition secretary" as login
login: <img:./images/5_competitionSecretaryMain.png>

[*] --> launch
note on link
  launch
end note

launch --> login
note on link
  login
end note

state " " as showCompetitions
showCompetitions: <img:./images/5_1_showCompetitionsCompetitionSecretary.png>

state " " as editCompetition
editCompetition: <img:./images/5_1_1_editBatchCompetitionSecretary.png>


login --> showCompetitions
note on link
  showCompetitions
end note


showCompetitions --> editCompetition
note on link
  editCompetition
end note

editCompetition --> editCompetition
note on link
  showBatches
end note

state " " as playBatch
playBatch:  <img:./images/5_1_1_1_competitionSecretaryPlay.png>


state secretaryCompetitionFork <<fork>>

editCompetition --> secretaryCompetitionFork

secretaryCompetitionFork --> playBatch
note on link
  showBatchInPlay
end note

playBatch --> playBatch
note on link
    editLiftValue
    editWeightChange
    showLifterCategory
    startTimer
    pauseTimer
    resumeTimer
    setDurationTimer
    stopTimer
end note

state " " as warmupArea
warmupArea: <img:./images/5_1_1_2_warmupArea.png>


secretaryCompetitionFork ---> warmupArea
note on link
  showBatchInPlay
end note

state " " as liftView
liftView: <img:./images/5_1_1_3_liftView.png>

state " " as timerKeeperView
timerKeeperView: <img:./images/5_1_1_4_timeKeeper.png>



state " " as timer
timer: <img:./images/5_1_1_5_timer.png>


secretaryCompetitionFork ----> liftView
note on link
  showLift
end note

secretaryCompetitionFork -----> timerKeeperView
note on link
    startTimer
    pauseTimer
    resumeTimer
    setDurationTimer
    stopTimer
end note

secretaryCompetitionFork ------> timer
note on link
  showLift
  showTimer
end note

@enduml