@startuml
state SHOWED_RESULTS : (Finished batch previously choosen)
state SHOWED_COMPETITION
state CHOSEN_BATCH
state enterDownloadCHC <<choice>>
state enterFinalStateCHC <<choice>>
state downloadResults {
  [*] --> [*]
  note on link
    System downloads a file
    with the results
  end note
}

state "SHOWED_RESULTS" as SHOWED_RESULTS_F
state "SHOWED_COMPETITION" as SHOWED_COMPETITION_F

SHOWED_RESULTS --> enterDownloadCHC
SHOWED_COMPETITION --> CHOSEN_BATCH
note on link
  User chooses a 
  finished batch from 
  the showed batches
end note

CHOSEN_BATCH --> enterDownloadCHC

enterDownloadCHC --> downloadResults
note on link
  User requests to:
  * downloadResults
end note

downloadResults --> enterFinalStateCHC : From what state did\nthe user request to\ndownload results?

enterFinalStateCHC --> SHOWED_RESULTS_F : [From\nSHOWED_RESULTS]
enterFinalStateCHC --> SHOWED_COMPETITION_F : [From\nSHOWED_COMPETITION]

footer \n\n\n Especificación del caso de uso "downloadResults"
@enduml
