@startuml
'https://plantuml.com/object-diagram

object Competition
object Batch
object Iteration
object Lift
object Athlete
object Bar
object "Bar announcement" as BarAnnouncement
object "Lift change time" as LiftChangeTime

object AthleteAnouncement
object NextLift
object FollowingLift

AthleteAnouncement *-- NextLift
AthleteAnouncement *-- FollowingLift
NextLift o-- Athlete
FollowingLift o-- Athlete


Competition *-- Batch
Batch *-- "1..n" Iteration
Iteration --> BarAnnouncement
BarAnnouncement --> AthleteAnouncement
AthleteAnouncement *-- LiftChangeTime


@enduml
