@startuml
"Competition" "1" *--> "3" "Phase"
"Competition" "n" o--> "n" "Person"
"Person" <|-- "Athlete"
"Athlete" <|-- "Male"
"Athlete" <|-- "Female"
"Person" <|-- "Judge"
"Person" <|-- "Competition secretary"
"Phase" <|-- "Weighing"
"Phase" <|-- "Development""
"Phase" <|-- "Classification"
"Weighing" --> "Development""
"Development"" --> "Classification"
"Classification" "1" o--> "n" "Olympic total"
"Weighing" o--> "Weight"
"Weight" <|-- "Body weight"
"Weight" <|-- "Opener"
"Development"" "1" *--> "n" "Batch"
"Batch" <|-- "Male batch"
"Batch" <|-- "Female batch"
"Male" "n" --> "1" "Male batch"
"Female" "n" --> "1" "Female batch"
"Batch" "1" *--> "n" "Iteration"
"Iteration" "1" *--> "2" "Step"
"Step" <|-- "Athletes announcement"
"Step" <|-- "Lift"
"Lift" <|-- "Null"
"Lift" <|-- "Valid"
"Valid" "n" --> "1" "Olympic total"
"Lift" --> "Countdown"
"Countdown" <|-- "60 s"
"Countdown" <|-- "120 s"
"Athletes announcement" --> "Lift"
"Mode" <|-- "Snatch"
"Mode" <|-- "Clean & jerk"
"Iteration" "1" --> "1" "Mode"
"Category" ..> "Body weight"
"Category" ..> "Athlete age"
"Bar" <|-- "Male bar"
"Bar" <|-- "Female bar"
"Bar" "1" o--> "2..2n" "Plate"
"Male batch" ..> "Male bar"
"Female batch" ..> "Female bar"
"Lift" --> "Bar"
"Lift" --> "Plate"

"Competition" --> "Scoring mode"
"Scoring mode" <|-- "By categories"
"Scoring mode" <|-- "All against all"

"Scoring calculation" <|-- "By olympic total"
"Scoring calculation" <|-- "Sinclair coefficient"

"By olympic total" ..> "Olympic total"
"Sinclair coefficient" ..> "Athlete age"
"Sinclair coefficient" ..> "Olympic total"

"Scoring mode" --> "Scoring calculation"
"By categories" --> "By olympic total"
"All against all" --> "Sinclair coefficient"

"By categories" o--> "Category"

"Athlete" "1" --> "1" "Winner"
"Competition" o--> "Winner"
"Winner" ..> "Scoring calculation"
@enduml
