@startuml
state LAUNCHED
state SPECTATOR_DASHBOARD
state OPENED_DASHBOARD
state COMPETITIONS_MANAGEMENT
state BATCH_MANAGEMENT
state BATCH_IN_PLAY
state FINISHED_BATCH

state logoutChoice <<choice>>

[*] --> LAUNCHED
note on link
  launch
end note

LAUNCHED --> SPECTATOR_DASHBOARD
note on link
  showCompetitions
  showBatchInscriptions
  showBatchWeightins
  showFinishedBatches
  showLiveBatchInPlay
  showResults
  downloadResults
end note

SPECTATOR_DASHBOARD --> OPENED_DASHBOARD
note on link
  login
end note


OPENED_DASHBOARD --> COMPETITIONS_MANAGEMENT
note on link
  showCompetitions
end note

COMPETITIONS_MANAGEMENT --> OPENED_DASHBOARD
COMPETITIONS_MANAGEMENT --> COMPETITIONS_MANAGEMENT


COMPETITIONS_MANAGEMENT --> BATCH_MANAGEMENT
note on link
  showBatches
end note

BATCH_MANAGEMENT --> BATCH_MANAGEMENT
note on link
  introduceWeighinData
end note


BATCH_MANAGEMENT --> BATCH_IN_PLAY
note on link
  initPlay
end note

BATCH_IN_PLAY --> BATCH_IN_PLAY
note on link
  editLiftValue
  editWeightChange
  showLifterCategory
  startTimer
  pauseTimer
  resumeTimer
  setDurationTimer
  stopTimer
end note

BATCH_IN_PLAY --> FINISHED_BATCH
note on link
  finishPlay
end note

FINISHED_BATCH --> FINISHED_BATCH
note on link
 generateAct
 downloadAct
 createClassifications
 downloadClassifications
end note

BATCH_MANAGEMENT ---> logoutChoice
BATCH_IN_PLAY ---> logoutChoice
FINISHED_BATCH ---> logoutChoice

logoutChoice --> [*]
note on link
 logout
end note

footer Diagrama de contexto del actor secretario de competición
@enduml