@startuml
state INITIAL
state OPENED_DASHBOARD
state CREATED_CLUBS
state CREATED_ORGANIZERS
state CREATED_INSCRIBERS
state CREATED_CATEGORIES
state OPENED_INSCRIPTIONS
state CREATED_COMPETITIONS
state INSCRIBED_LIFTERS
state CREATED_BATCH
state BATCH_IN_PLAY
state FINISHED_BATCH
state OPENED_SPECTATOR_DASHBOARD

[*] --> INITIAL
INITIAL --> OPENED_DASHBOARD
note on link
  login
  signin
end note

OPENED_DASHBOARD --> CREATED_CLUBS
note on link
  showClubs
end note
CREATED_CLUBS --> OPENED_DASHBOARD


OPENED_DASHBOARD --> CREATED_ORGANIZERS
note on link
  showOrganizers
end note

CREATED_ORGANIZERS --> CREATED_ORGANIZERS
note on link
  editOrganizer
  deleteOrganizer
end note
CREATED_ORGANIZERS --> OPENED_DASHBOARD


OPENED_DASHBOARD --> CREATED_INSCRIBERS
note on link
  showInscribers
end note
CREATED_INSCRIBERS --> OPENED_DASHBOARD

CREATED_INSCRIBERS --> CREATED_INSCRIBERS
note on link
  editInscriber
  deleteInscriber
end note

OPENED_DASHBOARD --> CREATED_CATEGORIES
note on link
  showCategories
end note

CREATED_CATEGORIES --> CREATED_CATEGORIES
note on link
  editCategory
  deleteCategory
end note
CREATED_CATEGORIES --> OPENED_DASHBOARD


CREATED_CLUBS --> CREATED_CLUBS
note on link
  editClub
  deleteClub
end note


INSCRIBED_LIFTERS --> INSCRIBED_LIFTERS
note on link
  inscribeLifter
  uninscribeLifter
end note


CREATED_ORGANIZERS --> OPENED_INSCRIPTIONS
note on link
  openInscriptions
end note


OPENED_INSCRIPTIONS --> INSCRIBED_LIFTERS
note on link
  showInscribedLifters
end note

OPENED_INSCRIPTIONS --> CLOSED_INSCRIPTIONS
note on link
  closeInscriptions
end note

CLOSED_INSCRIPTIONS --> CLOSED_INSCRIPTIONS
note on link
  draw_lifters
end note


OPENED_DASHBOARD --> CREATED_COMPETITIONS
note on link
  showCompetitions
end note

CREATED_COMPETITIONS --> OPENED_DASHBOARD
CREATED_COMPETITIONS --> CREATED_COMPETITIONS
note on link
  editCompetition
  deleteCompetition
end note

CREATED_COMPETITIONS --> CREATED_BATCH
note on link
  showBatches
end note

CREATED_BATCH --> CREATED_BATCH
note on link
  editBatch
  deleteBatch
  assignLifterToBatch
  unassignLifterToBatch
  introduceWeighinData
end note


CREATED_BATCH --> BATCH_IN_PLAY
note on link
  initPlay
end note

BATCH_IN_PLAY --> BATCH_IN_PLAY
note on link
  editLiftValue
  editWeightChange
  showLifterCategory
  startTimer
  pauseTimer
  resumeTimer
  setDurationTimer
  stopTimer
end note

BATCH_IN_PLAY --> FINISHED_BATCH
note on link
  finishPlay
end note

FINISHED_BATCH --> FINISHED_BATCH
note on link
 generateAct
 downloadAct
 createClassifications
 downloadClassifications
end note


[*] --> OPENED_SPECTATOR_DASHBOARD
note on link
  showCompetitions
  showBatchInscriptions
  showBatchWeightins
  showFinishedBatches
  showLiveBatchInPlay
  showResults
  downloadResults
end note



CREATED_CLUBS ---> [*]
note on link
 logout
end note
CREATED_ORGANIZERS ---> [*]
note on link
 logout
end note
CREATED_INSCRIBERS ---> [*]
note on link
 logout
end note
CREATED_CATEGORIES ---> [*]
note on link
 logout
end note

OPENED_INSCRIPTIONS ---> [*]
note on link
 logout
end note
INSCRIBED_LIFTERS ---> [*]
note on link
 logout
end note
CLOSED_INSCRIPTIONS ---> [*]
note on link
 logout
end note
CREATED_BATCH ---> [*]
note on link
 logout
end note
BATCH_IN_PLAY ---> [*]
note on link
 logout
end note
FINISHED_BATCH ---> [*]
note on link
 logout
end note
@enduml