@startuml
state LAUNCHED
state SPECTATOR_DASHBOARD
state OPENED_DASHBOARD
state CLUBS_MANAGEMENT
state ORGANIZERS_MANAGEMENT
state INSCRIBERS_MANAGEMENT
state CATEGORIES_MANAGEMENT
state LIFTERS_MANAGEMENT
state logoutChoice <<choice>>

[*] --> LAUNCHED
note on link
  launch
end note

LAUNCHED --> SPECTATOR_DASHBOARD
note on link
  showCompetitions
  showBatchInscriptions
  showBatchWeightins
  showFinishedBatches
  showLiveBatchInPlay
  showResults
  downloadResults
end note

SPECTATOR_DASHBOARD --> OPENED_DASHBOARD
note on link
  login
end note

OPENED_DASHBOARD --> CLUBS_MANAGEMENT
note on link
  showClubs
end note
CLUBS_MANAGEMENT --> OPENED_DASHBOARD


OPENED_DASHBOARD --> ORGANIZERS_MANAGEMENT
note on link
  showOrganizers
end note

ORGANIZERS_MANAGEMENT --> ORGANIZERS_MANAGEMENT
note on link
  editOrganizer
  deleteOrganizer
end note
ORGANIZERS_MANAGEMENT --> OPENED_DASHBOARD


OPENED_DASHBOARD --> INSCRIBERS_MANAGEMENT
note on link
  showInscribers
end note
INSCRIBERS_MANAGEMENT --> OPENED_DASHBOARD

INSCRIBERS_MANAGEMENT --> INSCRIBERS_MANAGEMENT
note on link
  editInscriber
  deleteInscriber
end note

OPENED_DASHBOARD --> CATEGORIES_MANAGEMENT
note on link
  showCategories
end note

CATEGORIES_MANAGEMENT --> CATEGORIES_MANAGEMENT
note on link
  editCategory
  deleteCategory
end note
CATEGORIES_MANAGEMENT --> OPENED_DASHBOARD


CLUBS_MANAGEMENT --> CLUBS_MANAGEMENT
note on link
  editClub
  deleteClub
end note


LIFTERS_MANAGEMENT --> LIFTERS_MANAGEMENT
note on link
  inscribeLifter
  uninscribeLifter
end note


ORGANIZERS_MANAGEMENT --> OPENED_INSCRIPTIONS
note on link
  openInscriptions
end note


OPENED_INSCRIPTIONS --> LIFTERS_MANAGEMENT
note on link
  showInscribedLifters
end note

OPENED_INSCRIPTIONS --> CLOSED_INSCRIPTIONS
note on link
  closeInscriptions
end note

CLOSED_INSCRIPTIONS --> CLOSED_INSCRIPTIONS
note on link
  draw_lifters
end note

CLUBS_MANAGEMENT ---> logoutChoice
ORGANIZERS_MANAGEMENT ---> logoutChoice
INSCRIBERS_MANAGEMENT ---> logoutChoice
CATEGORIES_MANAGEMENT ---> logoutChoice
OPENED_INSCRIPTIONS ---> logoutChoice
LIFTERS_MANAGEMENT ---> logoutChoice
CLOSED_INSCRIPTIONS ---> logoutChoice

logoutChoice --> [*]
note on link
 logout
end note

footer \n\n\n Diagrama de contexto del actor secretario de competicion
@enduml