@startuml
state SHOWED_CATEGORIES
state "SHOWED_CATEGORIES" as SHOWED_CATEGORIES_F
state deleteCategory {
  state " " as SHOWED_CATEGORIES_TO_BE_DELETED
  state " " as CHOSEN_CATEGORY
  state " " as CATEGORY_DELETED

  [*] --> SHOWED_CATEGORIES_TO_BE_DELETED
  note on link
    System shows:
    * categories name

    System allows to:
    * cancel
  end note
  
  SHOWED_CATEGORIES_TO_BE_DELETED --> CHOSEN_CATEGORY
  note on link
    Organization Secretary
    chooses an category
  end note

  SHOWED_CATEGORIES_TO_BE_DELETED -down-> SHOWED_CATEGORIES_F
  note on link
    Organization Secretary
    requests to:
    * cancel
  end note

  CHOSEN_CATEGORY --> CATEGORY_DELETED
  note on link
    System deletes the
    chosen category
  end note

  CATEGORY_DELETED --> [*]
  note on link
    System shows:
    * active categories indicator
    * categories name
    * categories competition type
    * categories gender
    * categories minimum age
    * categories maximum age
    * categories bodyweight categories

    System allows to:
    * deleteCategory
    * editCategory
    * showClubs
    * showInscribers
    * showOrganizers
    * logout
  end note
}

SHOWED_CATEGORIES --> deleteCategory
note on link
  Organization Secretary
  requests to:
  * deleteCategory
end note

deleteCategory ------> SHOWED_CATEGORIES_F

footer \n\n\n Especificación del caso de uso "deleteCategory"
@enduml
