@startuml
state SHOWED_CATEGORIES

state deleteCategory {
  state " " as SHOWED_CATEGORIES_TO_BE_DELETED
  state " " as CHOSEN_CATEGORY
  state " " as CATEGORY_DELETED

  [*] --> SHOWED_CATEGORIES_TO_BE_DELETED
  note on link
    System shows:
    * categories name
  end note
  
  SHOWED_CATEGORIES_TO_BE_DELETED --> CHOSEN_CATEGORY
  note on link
    User chooses a category
  end note

  CHOSEN_CATEGORY --> CATEGORY_DELETED
  note on link
    System deletes the
    chosen category
  end note

  CATEGORY_DELETED --> [*]
  note on link
    System shows:
    * active categories indicator
    * categories name
    * categories competition type
    * categories gender
    * categories minimum age
    * categories maximum age
    * categories bodyweight categories

    System allows to:
    * deleteCategory
    * editCategory
    * showClubs
    * showOrganizers
    * showInscribers
    * logout
  end note
}

state "SHOWED_CATEGORIES" as SHOWED_CATEGORIES_F

SHOWED_CATEGORIES --> deleteCategory
note on link
  User requests to:
  * deleteCategory
end note

deleteCategory --> SHOWED_CATEGORIES_F

footer \n\n\n Especificación del caso de uso "deleteCategory"
@enduml
