@startuml
state SHOWED_CATEGORIES
state CHOSEN_CATEGORY
state editCategory {
  state createOrModifyCHC <<choice>>
  state " " as providedCategory
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  [*] --> createOrModifyCHC
  createOrModifyCHC --> providedCategory : [category chosen]
  createOrModifyCHC --> createOrModifyCHC2 : [create category]
  providedCategory --> showedData
  note on link
    System shows:
    * Current category data
  end note
  showedData --> createOrModifyCHC2 : [modify category]
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * The competition type
    * Minimum age (included)
    * Maximum age (included)
    * Gender
    * Bodyweight categories

    System allows to:
    * cancel
  end note
  pendingData --> showCategories
  note on link
    User requests to:
    * cancel
  end note
  showCategories --> SHOWED_CATEGORIES_F
  pendingData --> providedData
  note on link
    User provides:
    * The competition type
    * Minimum age (included)
    * Maximum age (included)
    * Gender
    * Bodyweight categories
  end note
  providedData --> [*]
  note on link
    System allows to:
    * showCategories
  end note
}
state EDITED_CATEGORY
state showCategories
state "SHOWED_CATEGORIES" as SHOWED_CATEGORIES_F

SHOWED_CATEGORIES --> CHOSEN_CATEGORY
note on link
  User chooses a category 
  at showed categories
end note

CHOSEN_CATEGORY --> editCategory
note on link
  User requests to:
  * editCategory
end note

editCategory --> EDITED_CATEGORY

footer \n\n\n Especificación del caso de uso "editCategory"
@enduml
