@startuml
state SHOWED_CATEGORIES
state editCategory {
  state " " as SHOWED_CATEGORIES_TO_BE_EDITED
  state createOrModifyCHC <<choice>>
  state " " as providedCategory
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  state " " as savedData
  [*] --> SHOWED_CATEGORIES_TO_BE_EDITED
  note on link
    System shows:
    * categories name

    System allows to:
    * cancel
  end note

  SHOWED_CATEGORIES_TO_BE_EDITED --> createOrModifyCHC : Modify or create category?

  SHOWED_CATEGORIES_TO_BE_EDITED --> SHOWED_CATEGORIES_F
  note on link
    User requests to:
    * cancel
  end note

  createOrModifyCHC --> providedCategory : [chose category]
  createOrModifyCHC --> createOrModifyCHC2 : [create category]
  providedCategory --> showedData
  note on link
    System shows:
    * category name
    * category competition type
    * category gender
    * category minimum age
    * category maximum age
    * category bodyweight categories
  end note
  showedData --> createOrModifyCHC2 : [modify category -- añadir el actor quiere modificar - (quitarla y dajarla al rombo)]
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * name
    * competition type
    * minimum age (included)
    * maximum age (included)
    * gender
    * bodyweight categories

    System allows to:
    * cancel
  end note
  pendingData --> SHOWED_CATEGORIES_F
  note on link
    User requests to:
    * cancel
  end note

  pendingData --> providedData
  note on link
    User provides:
    * name
    * competition type
    * minimum age (included)
    * maximum age (included)
    * gender
    * bodyweight categories

    System allows to:
    * cancel
  end note

  providedData --> savedData
  note on link
    User saves 
    provided data
  end note

  providedData --> SHOWED_CATEGORIES_F
  note on link
    User requests to:
    * cancel
  end note

  savedData --> [*]
  note on link
    System allows to:
    * showCategories -> quitarla xq esto va automáticamente
    * editCategories
  end note
}
state EDITED_CATEGORY
state "SHOWED_CATEGORIES" as SHOWED_CATEGORIES_F : State before the user\nrequired "editCategory"

SHOWED_CATEGORIES --> editCategory
note on link
  User requests to:
  * editCategory
end note

editCategory --> EDITED_CATEGORY

footer \n\n\n Especificación del caso de uso "editCategory"
@enduml
