@startuml
state LOGGED_IN
state EDITED_CLUB
state SHOWED_CATEGORIES
state SHOWED_ORGANIZERS
state SHOWED_INSCRIBERS

state enterShowClubsCHC <<choice>>

state showClubs {
  [*] --> [*]
  note on link
    System shows:
    * active clubs indicator
    * clubs name

    System allows to:
    * deleteClub
    * editClub
    * showCategories
    * showOrganizers
    * showInscribers
    * logout
  end note
}
state SHOWED_CLUBS

LOGGED_IN --> enterShowClubsCHC
EDITED_CLUB --> enterShowClubsCHC
SHOWED_CATEGORIES --> enterShowClubsCHC
SHOWED_ORGANIZERS --> enterShowClubsCHC
SHOWED_INSCRIBERS --> enterShowClubsCHC

enterShowClubsCHC --> showClubs
note on link
  User requests to:
  * showClubs
end note
showClubs --> SHOWED_CLUBS

footer \n\n\n Especificación del caso de uso "showClubs"
@enduml
