@startuml
state SHOWED_CLUBS

state deleteClub {
  state " " as SHOWED_CLUBS_TO_BE_DELETED
  state " " as CHOSEN_CLUB
  state " " as CLUB_DELETED

  [*] --> SHOWED_CLUBS_TO_BE_DELETED
  note on link
    System shows:
    * clubs name
  end note
  
  SHOWED_CLUBS_TO_BE_DELETED --> CHOSEN_CLUB
  note on link
    User chooses a club
  end note

  CHOSEN_CLUB --> CLUB_DELETED
  note on link
    System deletes the
    chosen club
  end note

  CLUB_DELETED --> [*]
  note on link
    System shows:
    * active clubs indicator
    * clubs name

    System allows to:
    * deleteClub
    * editClub
    * showCategories
    * showOrganizers
    * showInscribers
    * logout
  end note
}

state "SHOWED_CLUBS" as SHOWED_CLUBS_F

SHOWED_CLUBS --> deleteClub
note on link
  User requests to:
  * deleteClub
end note

deleteClub --> SHOWED_CLUBS_F

footer \n\n\n Especificación del caso de uso "deleteClub"
@enduml
