@startuml
state SHOWED_CLUBS
state editClub {
  state " " as SHOWED_CLUBS_TO_BE_EDITED
  state createOrModifyCHC <<choice>>
  state " " as providedClub
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  state " " as savedData
  [*] --> SHOWED_CLUBS_TO_BE_EDITED
  note on link
    System shows:
    * clubs name

    System allows to:
    * cancel
  end note

  SHOWED_CLUBS_TO_BE_EDITED --> createOrModifyCHC : Modify or create club?

  SHOWED_CLUBS_TO_BE_EDITED --> SHOWED_CLUBS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  createOrModifyCHC --> providedClub : [chose club]
  createOrModifyCHC --> createOrModifyCHC2 : [create club]
  providedClub --> showedData
  note on link
    System shows:
    * club name
  end note
  showedData --> createOrModifyCHC2 : [modify club]
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * name

    System allows to:
    * cancel
  end note
  pendingData --> SHOWED_CLUBS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  pendingData --> providedData
  note on link
    Organization Secreatary
    provides:
    * name

    System allows to:
    * cancel
  end note

  providedData --> savedData
  note on link
    Organization Secreatary
    saves provided data
  end note

  providedData --> SHOWED_CLUBS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  savedData --> [*]
  note on link
    System allows to:
    * showClubs
    * editClub
  end note
}
state EDITED_CLUB
state "SHOWED_CLUBS" as SHOWED_CLUBS_F : State before the user\nrequired "editClub"

SHOWED_CLUBS --> editClub
note on link
  Organization Secreatary
  requests to:
  * editClub
end note

editClub --> EDITED_CLUB

footer \n\n\n Especificación del caso de uso "editClub"
@enduml
