@startuml
state SHOWED_ORGANIZERS
state "SHOWED_ORGANIZERS" as SHOWED_ORGANIZERS_F
state deleteOrganizer {
  state " " as SHOWED_ORGANIZERS_TO_BE_DELETED
  state " " as CHOSEN_ORGANIZER
  state " " as ORGANIZER_DELETED

  [*] --> SHOWED_ORGANIZERS_TO_BE_DELETED
  note on link
    System shows:
    * organizers name

    System allows to:
    * cancel
  end note
  
  SHOWED_ORGANIZERS_TO_BE_DELETED --> CHOSEN_ORGANIZER
  note on link
    User chooses an organizer
  end note

  SHOWED_ORGANIZERS_TO_BE_DELETED -down-> SHOWED_ORGANIZERS_F
  note on link
    User requests to:
    * cancel
  end note

  CHOSEN_ORGANIZER --> ORGANIZER_DELETED
  note on link
    System deletes the
    chosen organizer
  end note

  ORGANIZER_DELETED --> [*]
  note on link
    System shows:
    * active organizers indicator
    * organizers name

    System allows to:
    * deleteOrganizer
    * editOrganizer
    * showCategories
    * showClubs
    * showInscribers
    * logout
  end note
}

SHOWED_ORGANIZERS --> deleteOrganizer
note on link
  User requests to:
  * deleteOrganizer
end note

deleteOrganizer ------> SHOWED_ORGANIZERS_F

footer \n\n\n Especificación del caso de uso "deleteOrganizer"
@enduml
