@startuml
state SHOWED_ORGANIZERS
state editOrganizer {
  state " " as SHOWED_ORGANIZERS_TO_BE_EDITED
  state createOrModifyCHC <<choice>>
  state " " as providedOrganizer
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  state " " as savedData
  [*] --> SHOWED_ORGANIZERS_TO_BE_EDITED
  note on link
    System shows:
    * organizers name

    System allows to:
    * cancel
  end note

  SHOWED_ORGANIZERS_TO_BE_EDITED --> createOrModifyCHC : Modify or create organizer?

  SHOWED_ORGANIZERS_TO_BE_EDITED --> SHOWED_ORGANIZERS_F
  note on link
    User requests to:
    * cancel
  end note

  createOrModifyCHC --> providedOrganizer : [chose organizer]
  createOrModifyCHC --> createOrModifyCHC2 : [create organizer]
  providedOrganizer --> showedData
  note on link
    System shows:
    * organizer name
  end note
  showedData --> createOrModifyCHC2 : [modify organizer]
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * name

    System allows to:
    * cancel
  end note
  pendingData --> SHOWED_ORGANIZERS_F
  note on link
    User requests to:
    * cancel
  end note

  pendingData --> providedData
  note on link
    User provides:
    * name

    System allows to:
    * cancel
  end note

  providedData --> savedData
  note on link
    User saves 
    provided data
  end note

  providedData --> SHOWED_ORGANIZERS_F
  note on link
    User requests to:
    * cancel
  end note

  savedData --> [*]
  note on link
    System allows to:
    * showOrganizers
    * editOrganizer
  end note
}
state EDITED_ORGANIZER
state "SHOWED_ORGANIZERS" as SHOWED_ORGANIZERS_F : State before the user\nrequired "editOrganizer"

SHOWED_ORGANIZERS --> editOrganizer
note on link
  User requests to:
  * editOrganizer
end note

editOrganizer --> EDITED_ORGANIZER

footer \n\n\n Especificación del caso de uso "editOrganizer"
@enduml
