@startuml
state LOGGED_IN
state EDITED_INSCRIBERS
state SHOWED_CATEGORIES
state SHOWED_CLUBS
state SHOWED_ORGANIZERS

state enterShowInscriberCHC <<choice>>

state showInscribers {
  [*] --> [*]
  note on link
    System shows:
    * active inscribers indicator
    * inscribers name

    System allows to:
    * deleteInscriber
    * editInscriber
    * showCategories
    * showClubs
    * showOrganizers
    * logout
  end note
}
state SHOWED_INSCRIBERS

LOGGED_IN --> enterShowInscriberCHC
EDITED_INSCRIBERS --> enterShowInscriberCHC
SHOWED_CATEGORIES --> enterShowInscriberCHC
SHOWED_CLUBS --> enterShowInscriberCHC
SHOWED_ORGANIZERS --> enterShowInscriberCHC

enterShowInscriberCHC --> showInscribers
note on link
  Organization Secreatary
  requests to:
  * showInscribers
end note
showInscribers --> SHOWED_INSCRIBERS

footer \n\n\n Especificación del caso de uso "showInscribers"
@enduml
