@startuml
state LOGGED_IN
state EDITED_INSCRIBERS
state SHOWED_CATEGORIES
state SHOWED_CLUBS
state SHOWED_ORGANIZERS

state enterShowInscriberCHC <<choice>>

state showInscribers {
  [*] --> [*]
  note on link
    System shows:
    * inscribers

    For each showed inscriber, 
    system allows to:
    * deleteInscriber
    * editInscriber

    System allows to:
    * showCategories
    * showClubs
    * showOrganizers
    * logout
  end note
}
state SHOWED_INSCRIBERS

LOGGED_IN --> enterShowInscriberCHC
EDITED_INSCRIBERS --> enterShowInscriberCHC
SHOWED_CATEGORIES --> enterShowInscriberCHC
SHOWED_CLUBS --> enterShowInscriberCHC
SHOWED_ORGANIZERS --> enterShowInscriberCHC

enterShowInscriberCHC --> showInscribers
note on link
  User requests to:
  * showInscribers
end note
showInscribers --> SHOWED_INSCRIBERS

footer \n\n\n Especificación del caso de uso "showInscribers"
@enduml
