@startuml
state SHOWED_INSCRIBERS
state CHOSEN_INSCRIBER

state deleteInscriber {
  [*] --> [*]
  note on link
    System allows to:
    * showInscribers
  end note
}

state showInscribers
state "SHOWED_INSCRIBERS" as SHOWED_INSCRIBERS_F

SHOWED_INSCRIBERS --> CHOSEN_INSCRIBER
note on link
  User chooses a inscriber 
  at showed inscribers
end note

CHOSEN_INSCRIBER --> deleteInscriber
note on link
  User requests to:
  * deleteInscriber
end note

deleteInscriber --> showInscribers
showInscriber --> SHOWED_INSCRIBER_F

footer \n\n\n Especificación del caso de uso "deleteInscriber"
@enduml
