@startuml
state SHOWED_INSCRIBERS

state deleteInscriber {
  state " " as SHOWED_INSCRIBERS_TO_BE_DELETED
  state " " as CHOSEN_INSCRIBER
  state " " as INSCRIBER_DELETED

  [*] --> SHOWED_INSCRIBERS_TO_BE_DELETED
  note on link
    System shows:
    * categories to be deleted
  end note
  
  SHOWED_INSCRIBERS_TO_BE_DELETED --> CHOSEN_INSCRIBER
  note on link
    User chooses an inscriber 
    to be deleted
  end note

  CHOSEN_INSCRIBER --> INSCRIBER_DELETED
  note on link
    System deletes the
    chosen inscriber
  end note

  INSCRIBER_DELETED --> [*]
  note on link
    System shows existing
    inscribers
  end note
}

state "SHOWED_INSCRIBERS" as SHOWED_INSCRIBERS_F

SHOWED_INSCRIBERS --> deleteInscriber
note on link
  User requests to:
  * deleteInscriber
end note

deleteInscriber --> SHOWED_INSCRIBERS_F

footer \n\n\n Especificación del caso de uso "deleteInscriber"
@enduml
