@startuml
state SHOWED_INSCRIBERS
state CHOSEN_INSCRIBER
state editInscriber {
  state createOrModifyCHC <<choice>>
  state " " as providedInscriber
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  [*] --> createOrModifyCHC
  createOrModifyCHC --> providedInscriber : There is a chosen inscriber
  createOrModifyCHC --> createOrModifyCHC2 : The user is creating\na new inscriber
  providedInscriber --> showedData
  note on link
    System shows:
    * Current inscriber name
  end note
  showedData --> createOrModifyCHC2 : The user is modifying\na inscriber
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * Name

    System allows to:
    * cancel
  end note
  pendingData --> showInscribers
  note on link
    User requests to:
    * cancel
  end note
  showInscribers --> SHOWED_INSCRIBERS_F
  pendingData --> providedData 
  note on link
    User provides:
    * Name
  end note
  providedData --> [*]
  note on link
    System allows to:
    * showInscribers
  end note
}
state EDITED_INSCRIBER
state showInscribers
state "SHOWED_INSCRIBERS" as SHOWED_INSCRIBERS_F

SHOWED_INSCRIBERS --> CHOSEN_INSCRIBER
note on link
  User chooses a inscriber 
  at showed inscribers
end note

CHOSEN_INSCRIBER --> editInscriber
note on link
  User requests to:
  * editInscriber
end note

editInscriber --> EDITED_INSCRIBER

footer \n\n\n Especificación del caso de uso "editInscriber"
@enduml
