@startuml
state SHOWED_INSCRIBERS
state editInscriber {
  state " " as SHOWED_INSCRIBERS_TO_BE_EDITED
  state createOrModifyCHC <<choice>>
  state " " as providedInscriber
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  state " " as savedData
  [*] --> SHOWED_INSCRIBERS_TO_BE_EDITED
  note on link
    System shows:
    * inscribers name

    System allows to:
    * cancel
  end note

  SHOWED_INSCRIBERS_TO_BE_EDITED --> createOrModifyCHC : Modify or create inscriber?

  SHOWED_INSCRIBERS_TO_BE_EDITED --> SHOWED_INSCRIBERS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  createOrModifyCHC --> providedInscriber : [chose inscriber]
  createOrModifyCHC --> createOrModifyCHC2 : [create inscriber]
  providedInscriber --> showedData
  note on link
    System shows:
    * inscriber name
  end note
  showedData --> createOrModifyCHC2 : [modify inscriber]
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * name

    System allows to:
    * cancel
  end note
  pendingData --> SHOWED_INSCRIBERS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  pendingData --> providedData
  note on link
    Organization Secreatary
    provides:
    * name

    System allows to:
    * cancel
  end note

  providedData --> savedData
  note on link
    Organization Secreatary
    saves provided data
  end note

  providedData --> SHOWED_INSCRIBERS_F
  note on link
    Organization Secreatary
    requests to:
    * cancel
  end note

  savedData --> [*]
  note on link
    System allows đto:
    * showInscribers
    * editInscriber
  end note
}
state EDITED_INSCRIBER
state "SHOWED_INSCRIBERS" as SHOWED_INSCRIBERS_F : State before the user\nrequired "editInscriber"

SHOWED_INSCRIBERS --> editInscriber
note on link
  Organization Secreatary
  requests to:
  * editInscriber
end note

editInscriber --> EDITED_INSCRIBER

footer \n\n\n Especificación del caso de uso "editInscriber"
@enduml
