@startuml
state SHOWED_COMPETITIONS
state CHOSEN_COMPETITION
state SHOWED_BATCH_INSCRIPTIONS : (Competition previously choosen)
state SHOWED_BATCH_WEIGHINS : (Competition previously choosen)
state SHOWED_LIVE_BATCH_IN_PLAY : (Competition previously choosen)

state chooseCompetition <<choice>>

SHOWED_COMPETITIONS  --> CHOSEN_COMPETITION
note on link
  User chooses a 
  competition from the 
  showed competitions
end note

CHOSEN_COMPETITION --> chooseCompetition
SHOWED_BATCH_INSCRIPTIONS  --> chooseCompetition
SHOWED_BATCH_WEIGHINS  --> chooseCompetition
SHOWED_LIVE_BATCH_IN_PLAY  --> chooseCompetition

chooseCompetition --> showCompetition
note on link
  User requests to:
  * showCompetition
end note

state showCompetition {
  [*] --> [*]
  note on link
    System shows:
    * The batches info

    For each showed batch, 
    system allows to:
    * showBatchInscriptions

    For not pending batches,
    system allows to:
    * showBatchWeighins

    For all the finished batches,
    system allows to:
    * downloadResults

    Also, system allows to:
    * showLiveBatchInPlay
    * logout
  end note
}
state SHOWED_COMPETITION

showCompetition --> SHOWED_COMPETITION

footer \n\n\n Especificación del caso de uso "showCompetition"
@enduml
