@startuml
state SHOWED_COMPETITION
state CHOSEN_BATCH
state showBatchInscriptions {
  [*] --> [*]
  note on link
    System shows:
    * Inscripted lifters in batch
    
    System allows to:
    * showCompetition
    * logout
  end note
}
state SHOWED_BATCH_INSCRIPTIONS

SHOWED_COMPETITION --> CHOSEN_BATCH
note on link
  User chooses a batch
  from the batches at 
  showed competition
end note

CHOSEN_BATCH --> showBatchInscriptions
note on link
  User requests to:
  * showBatchInscriptions
end note

showBatchInscriptions --> SHOWED_BATCH_INSCRIPTIONS

footer \n\n\n Especificación del caso de uso "showBatchInscriptions"
@enduml
