@startuml
state SHOWED_COMPETITION
state CHOSEN_BATCH
state showBatchWeighins {
  [*] --> [*]
  note on link
    System shows:
    * All the weighins in batch
    
    System allows to:
    * showCompetition
    * logout
  end note
}
state SHOWED_BATCH_WEIGHINS

SHOWED_COMPETITION --> CHOSEN_BATCH
note on link
  User chooses a batch from
  the not pending batches 
  at showed competition
end note

CHOSEN_BATCH --> showBatchWeighins
note on link
  User requests to:
  * showBatchWeighins
end note

showBatchWeighins --> SHOWED_BATCH_WEIGHINS

footer \n\n\n Especificación del caso de uso "showBatchWeighins"
@enduml
