@startuml
state SHOWED_FINISHED_BATCHES
state DOWNLOADED_RESULTS
state enterResultsCHC <<choice>>

state showResults {
  state " " as pendingBatch
  state " " as providedBatch
  [*] --> pendingBatch
  note on link
    System requires:
    * A specific batch
  end note
  pendingBatch --> providedBatch
  note on link
    User provides:
    * A specific batch
  end note
  providedBatch --> [*]
  note on link
    System shows:
    * Selected batch results
    
    System allows to:
    * showCompetition
    * downloadResults
    * logout
  end note
}
state SHOWED_RESULTS

SHOWED_FINISHED_BATCHES --> enterResultsCHC
DOWNLOADED_RESULTS --> enterResultsCHC
enterResultsCHC --> showResults
note on link
  User requests to:
  * showResults
end note
showResults --> SHOWED_RESULTS

footer \n\n\n Especificación del caso de uso "showResults"
@enduml
