@startuml
left to right direction

package SpectatorManagement {
  usecase showCompetition
  usecase showBatchInscriptions
  usecase showBatchWeighins
  usecase showFinishedBatchs
  usecase showLiveBatchInPlay
  usecase showResults
  usecase downloadResults
  usecase launch
  usecase login
  usecase logout
}

User --> showCompetition
User --> showBatchInscriptions
User --> showBatchWeighins
User --> showFinishedBatchs
User --> showLiveBatchInPlay
User --> showResults
User --> downloadResults
User --> launch
User --> login
User --> logout

footer \n\nFigura 7. Casos de uso relacionados con el actor
@enduml