@startuml

left to right direction

package Clubs_Management {
    usecase showClubs
    usecase editClub
    usecase deleteClub
}

package OrganizersManagement {
  usecase showOrganizers
  usecase editOrganizer
  usecase deleteOrganizer
}

package InscribersManagement {
  usecase showInscribers
  usecase deleteInscriber
  usecase editInscriber
}

package CategoryManagement {
  usecase deleteCategory
  usecase editCategory
  usecase showCategories
}

OrganizationSecretary --> showClubs
OrganizationSecretary --> editClub
OrganizationSecretary --> deleteClub

OrganizationSecretary --> showOrganizers
OrganizationSecretary --> editOrganizer
OrganizationSecretary --> deleteOrganizer
OrganizationSecretary --> showOrganizers

OrganizationSecretary --> deleteInscriber
OrganizationSecretary --> editInscriber
OrganizationSecretary --> showInscribers

OrganizationSecretary --> deleteCategory
OrganizationSecretary --> editCategory
OrganizationSecretary --> showCategories

footer \n\nCasos de uso relacionados con el actor secretario de competición
@enduml