@startuml
left to right direction

actor Organizer as Organizer
actor Inscriber as Inscriber
actor OrganizationSecretary as OrganizationSecretary
actor Time as Time
actor TimeKeeper as TimeKeeper
actor Spectator as Spectator
actor CompetitionSecretary as CompetitionSecretary
actor User


package Admin_Management {
  usecase "Create/Modify club" as createClub
  usecase "Delete club" as deleteClub
  usecase "Manage clubs" as manageClubs

  usecase "Edit organizer" as createOrganizer
  usecase "Delete organizer" as deleteOrganizer
  usecase "Show organizers" as manageOrganizers

  usecase "Delete inscriber" as deleteInscriber
  usecase "Create/Modify inscriber" as createInscriber
  usecase "Manage inscribers" as manageInscribers
' falta el caso de uso visualizar TODO
  usecase "Toggle category availability" as toggleCategory
  usecase "Delete category" as deleteCategory
  usecase "Edit category" as createCategory
  usecase "Show categories" as manageCategories
}

manageClubs --> createClub
manageClubs --> deleteClub
OrganizationSecretary --> manageClubs

manageOrganizers --> deleteOrganizer
manageOrganizers --> createOrganizer
OrganizationSecretary --> manageOrganizers

manageInscribers --> deleteInscriber
manageInscribers --> createInscriber
OrganizationSecretary --> manageInscribers

OrganizationSecretary --> deleteCategory
OrganizationSecretary --> createCategory
OrganizationSecretary --> toggleCategory
OrganizationSecretary --> manageCategories

package COMPETITION_BUROCRACY {
  usecase "Open competition" as createCompetition
  ' Time lanza CerrarCompeticion
  usecase "Delete competition" as deleteCompetition
  usecase "Manage competition" as manageCompetition


  usecase "Draw athletes" as drawAthletes
  usecase "setCompetitionType" as setCompetitionType
  usecase "Set competition date" as setCompetitionDate
  usecase "Set competition location" as setCompetitionLocation
  usecase "Set number of batchs" as setNumberOfBatchs
  usecase "Set inscription period" as setInscriptionPeriod
  usecase "Set competition organizer" as setOrganizer
  usecase "Toggle competition visibility data" as toggle
  note right of toggle : Allows to see all athleted inscribed \nor just inscriber's club athletes

  usecase "Inscribe athlete" as inscribeAthlete
  usecase "Delete athlete" as uninscribeAthlete
  usecase "Show inscribed athletes" as showInscribedAthletes
  usecase "Generate classification" as generateClassification
  usecase "Manage athlete inscriptions" as manageAthleteInscriptions

  createCompetition --> setCompetitionDate
  createCompetition --> setInscriptionPeriod
  createCompetition --> setCompetitionLocation
  createCompetition --> setNumberOfBatchs
  createCompetition --> setCompetitionType
  createCompetition --> setOrganizer

  manageCompetition --> toggle
  manageCompetition ---> drawAthletes
  manageCompetition ---> deleteCompetition
  manageCompetition ----> createCompetition

  manageAthleteInscriptions --> inscribeAthlete
  manageAthleteInscriptions --> uninscribeAthlete
  manageAthleteInscriptions --> showInscribedAthletes
}

Organizer --> manageAthleteInscriptions
Inscriber --> manageAthleteInscriptions
Organizer --> manageCompetition
Organizer --> generateClassification

package BATCH {
  usecase "Configure batches" as createBatch
  'TODO quitar las flechas y set tecniacl officers etc etc lo llevas a un diagrama de estados
  'TODO meter la configuración de los atletas en esta parte
  usecase "Delete batch" as deleteBatch
  usecase "Set weighin time" as setBatchWeightInDate
  usecase "Set start time" as setBatchStartTime
  usecase "Set location" as setBatchLocation
  usecase "Set gender" as setGender
  usecase "Set number of platforms" as platformNumber
  usecase "Set technical officers" as setTecnicalOfficers

  createBatch ---> setBatchLocation
  createBatch ---> platformNumber
  createBatch ---> setBatchWeightInDate
  createBatch ---> setBatchStartTime
  createBatch ---> setGender
  createBatch ---> setTecnicalOfficers

  usecase "Assign athlete to batch" as assignAthleteToBatch
  usecase "Unassign athlete to batch" as unassignedAthleteToBatch

  usecase "Weighin introduction" as weighToAct
  usecase "Show athlete category" as showAthleteCategory
  usecase "Select athlete name" as writeDownAthleteName
  usecase "Write down athlete bodyweight" as writeDownAthleteBodyWeight
  usecase "Calculate athlete category" as calculateAthleteCategory
  usecase "Set lift status" as setLiftStatus
  usecase "Set lift value" as setLiftValue
  'son acciones
  usecase "Set lift weight change" as setLiftWeightChange
  usecase "Generate batch act" as generateBatchAct
  usecase "Upload batch handwritten acts" as uploadActs
  usecase "Upload batch handwritten weighing act" as uploadWeightAct
  usecase "Upload batch handwritten lifts" as uploadPlays
  usecase "Open batch"
  usecase "Play"
  uploadActs ---> uploadWeightAct
  uploadActs --> uploadPlays

  weighToAct --> writeDownAthleteName
  weighToAct --> writeDownAthleteBodyWeight
  weighToAct --> calculateAthleteCategory
}

Organizer --> createBatch
Organizer --> assignAthleteToBatch
Organizer --> unassignedAthleteToBatch
Organizer --> deleteBatch
Organizer --> uploadActs
CompetitionSecretary --> weighToAct
CompetitionSecretary --> setLiftStatus
CompetitionSecretary --> setLiftValue
CompetitionSecretary --> generateBatchAct
CompetitionSecretary --> setLiftWeightChange

package TIMER {
  usecase "Start timer" as startTimer
  usecase "Pause timer" as pauseTimer
  usecase "Resume timer" as resumeTimer
  usecase "Set timer duration" as setTimerDuration
  usecase "Stop timer" as stopTimer
}

TimeKeeper --> startTimer
TimeKeeper --> pauseTimer
TimeKeeper --> resumeTimer
TimeKeeper --> stopTimer
TimeKeeper --> setTimerDuration
Time --> stopTimer

CompetitionSecretary ---> startTimer
CompetitionSecretary ---> pauseTimer
CompetitionSecretary ---> resumeTimer
CompetitionSecretary ---> stopTimer
CompetitionSecretary ---> setTimerDuration


package SPECTATOR_VIEW {
  usecase "Show competition inscription" as showCompetitionData
  usecase "Show batch inscriptions" as showBatchInscriptions
  usecase "Show batch weighins" as showBatchWeighins
  usecase "Show batch results" as showFinishedBatchsData
  usecase "Show live batch in play" as showLiveBatchInPlay
  usecase "Show results" as showResults
  usecase "Download results" as downloadResults
}
Spectator --> showCompetitionData
Spectator --> showBatchInscriptions
Spectator --> showBatchWeighins
Spectator --> showFinishedBatchsData
Spectator --> showLiveBatchInPlay
Spectator --> showResults
Spectator --> downloadResults

'secretario ponerle como herencia de timekeerper y quitar las relaciones com time
@enduml