@startuml

actor Organizer as Organizer
actor Inscriber as Inscriber
actor OrganizationSecretary as OrganizationSecretary
actor Time as Time
actor TimeKeeper as TimeKeeper
actor Spectator as Spectator
actor CompetitionSecretary as CompetitionSecretary
actor User

package Log {
  usecase Login as login
  usecase Logout as logout
}

User -> login
User --> logout

User <|--- Organizer
User <|--- OrganizationSecretary
User <|--- CompetitionSecretary
User <|--- Spectator
CompetitionSecretary <|--- TimeKeeper
Organizer <|--- Inscriber

newpage
left to right direction

'package AdminManagement {

  package Clubs_Management {
      usecase "Show clubs" as showClubs
      usecase "Edit club" as editClub
      usecase "Delete club" as deleteClub
  }

  package OrganizersManagement {
    usecase "Show organizers" as showOrganizers
    usecase "Edit organizer" as editOrganizer
    usecase "Delete organizer" as deleteOrganizer
  }

  package InscribersManagement {
    usecase "Show inscribers" as showInscribers
    usecase "Delete inscriber" as deleteInscriber
    usecase "Edit inscriber" as editInscriber
  }

  package CategoryManagement {
    usecase "Toggle category availability" as toggleCategory
    usecase "Delete category" as deleteCategory
    usecase "Edit category" as editCategory
    usecase "Show categories" as showCategories
  }
'}

OrganizationSecretary --> showClubs
OrganizationSecretary --> editClub
OrganizationSecretary --> deleteClub

OrganizationSecretary --> showOrganizers
OrganizationSecretary --> editOrganizer
OrganizationSecretary --> deleteOrganizer
OrganizationSecretary --> showOrganizers

OrganizationSecretary --> deleteInscriber
OrganizationSecretary --> editInscriber
OrganizationSecretary --> showInscribers

OrganizationSecretary --> deleteCategory
OrganizationSecretary --> editCategory
OrganizationSecretary --> toggleCategory
OrganizationSecretary --> showCategories

newpage
left to right direction

package COMPETITION_BUREAUCRACY {
  usecase "Open inscriptions" as openInscriptions
  usecase "Close inscriptions" as closeInscriptions

  usecase "Delete competition" as deleteCompetition
  usecase "Edit competition" as editCompetition
  note right of editCompetition: Actions in state diagram would be \n -Set competition organizer \n -Set inscription period \n -Set number of batches \n -Set location \n -Set date \n - Set type

  usecase "Draw lifters" as drawLifters
  usecase "Inscribe lifter" as inscribeLifter
  usecase "Delete lifter" as uninscribeLifter
  usecase "Show inscribed lifters" as showInscribedLifter
  usecase "Generate classifications" as generateClassification
  usecase "Show classifications" as showClassifications
}

Time --> closeInscriptions
Organizer --> closeInscriptions
Organizer --> openInscriptions
Organizer --> drawLifters
Organizer --> deleteCompetition
Organizer --> editCompetition
Organizer --> generateClassification
Organizer --> showClassifications

Inscriber --> inscribeLifter
Inscriber --> uninscribeLifter
Inscriber --> showInscribedLifter


newpage
left to right direction

package BATCH {
  usecase "Show batches" as showBatches
  usecase "Edit batch" as editBatch
  note right of editBatch : Actions to state diagram \n -Set location \n -Set start time \n -Set weighin time \n -Set technical officers \n -Set platform numbers \n -Set gender

  usecase "Delete batch" as deleteBatch
  usecase "Assign lifter to batch" as assignLifterToBatch
  usecase "Unassign lifter to batch" as unassignedLifterToBatch

  usecase "Show athlete category" as showAthleteCategory
  usecase "Set lift status" as setLiftStatus
  usecase "Set lift value" as setLiftValue

  usecase "Set lift weight change" as setLiftWeightChange
  usecase "Generate act" as generateBatchAct
  usecase "Download act" as downloadAct
  usecase "Introduce weighin data" as introduceWeighinData
  note right of introduceWeighinData: After weighin \n-opening snatch \n -clean&jerk \n -bodyweight \n must be edited

  usecase "Init Play" as initPlay
  usecase "Finish play" as finishPlay

}

Organizer --> showBatches
Organizer --> editBatch
Organizer --> assignLifterToBatch
Organizer --> unassignedLifterToBatch
Organizer --> deleteBatch
Organizer --> introduceWeighinData
Organizer --> downloadAct

CompetitionSecretary --> setLiftStatus
CompetitionSecretary --> setLiftValue
CompetitionSecretary --> generateBatchAct
CompetitionSecretary --> setLiftWeightChange
CompetitionSecretary --> showAthleteCategory
CompetitionSecretary --> initPlay
CompetitionSecretary --> finishPlay

newpage
left to right direction

package TIMER {
  usecase "Start timer" as startTimer
  usecase "Pause timer" as pauseTimer
  usecase "Resume timer" as resumeTimer
  usecase "Set timer duration" as setTimerDuration
  usecase "Stop timer" as stopTimer
}

TimeKeeper --> startTimer
TimeKeeper --> pauseTimer
TimeKeeper --> resumeTimer
TimeKeeper --> stopTimer
TimeKeeper --> setTimerDuration
Time --> stopTimer


newpage
left to right direction

package SPECTATOR_VIEW {
  usecase "Show competition inscription" as showCompetitionData
  usecase "Show batch inscriptions" as showBatchInscriptions
  usecase "Show batch weighins" as showBatchWeighins
  usecase "Show batch results" as showFinishedBatchsData
  usecase "Show live batch in play" as showLiveBatchInPlay
  usecase "Show results" as showResults
  usecase "Download results" as downloadResults
}
Spectator --> showCompetitionData
Spectator --> showBatchInscriptions
Spectator --> showBatchWeighins
Spectator --> showFinishedBatchsData
Spectator --> showLiveBatchInPlay
Spectator --> showResults
Spectator --> downloadResults

'secretario ponerle como herencia de timekeerper y quitar las relaciones com time
@enduml