@startuml

title Priorización de casos de uso
left to right direction

note "Primera iteración: Jugar una tanda" as N1
usecase introduceWeighinData
usecase initPlay
usecase editLiftWeightChange
usecase editLiftStatus
usecase editLiftValue

' ============
newpage
left to right direction
note "Segunda iteración: gestión de categorías y completar jugar \nuna tanda añadiendo categoría de los levantadores" as N2
usecase editCategory
usecase deleteCategory
usecase showCategories
usecase showLifterCategory

' ============
newpage
'left to right direction

note "Tercera iteración: gestión del timer, contraseña y gestión de los distintos roles \ncon los que se puede acceder a la aplicación" as not

usecase start
usecase pause
usecase resume
usecase setDuration
usecase stop
usecase login
usecase logout


' ============
newpage
left to right direction
note "Cuarta iteración: gestión de competiciones y tandas" as N4

  usecase editCompetition
  usecase deleteCompetition
  usecase showCompetitions
  usecase editBatch
  usecase deleteBatch
  usecase showBatches

' ============
newpage
left to right direction

note "Quinta iteración: gestión de organizadores e inscriptores" as N5
  usecase editClub
  usecase showClubs
  usecase deleteClub
  usecase editInscriber
  usecase showInscribers
  usecase deleteInscriber
  usecase editOrganizers
  usecase showOrganizers
  usecase deleteOrganizers

' ============
newpage
left to right direction
note "Sexta iteración: inscribir levantadores, asignación de los mismos a tandas y sorteo" as N6

usecase inscribeLifter
usecase uninscribeLifter
usecase showInscribedLifters
usecase assignLifterToBatch
usecase unassignLifterToBatch
usecase drawLifters

' ============
newpage
left to right direction
note "Séptima iteración: generar y mostrar actas y clasificaciones" as N7

usecase createClassifications
usecase showClassifications
usecase createAct
usecase downloadAct

' ============
newpage
left to right direction
note "Octava iteración: resto de casos de uso" as N8



@enduml