@startuml

Organizer as organizer
Inscriber as inscriber
Admin as admin
Time as time
TimeJudge as timeJudge
Spectator as spectator
CompetitionSecretary as cs

newpage

left to right direction

Organizer --> (Create competition)
(Create competition) --> (Set competition date)
(Create competition) --> (Set competition location)
(Create competition) --> (Set number of bounds)
(Create competition) --> (Set inscription period)
Organizer --> (Delete competition)

usecase setCompetitionType as "Set competition type"
Organizer --> setCompetitionType
note right of setCompetitionType : Junior, Master, Senior...

Organizer --> (Toggle competition visibility data)

Inscriber --> (Inscribe athlete)
Inscriber --> (Uninscribe athlete)

Organizer --> (Inscribe athlete)
Organizer --> (Uninscribe athlete)


newpage
left to right direction
Organizer --> (Create bound)
Organizer --> (Delete bound)
(Create bound) --> (Set date)
(Create bound) --> (Set location)
(Create bound) --> (Set number of platforms)
(Create bound) --> (Set gender)
Organizer --> (Assign athlete to bound)
Organizer --> (Unassigned athlete to bound)

newpage
left to right direction

timeJudge --> (Start timer)
timeJudge --> (Pause timer)
timeJudge --> (Resume timer)
timeJudge --> (Stop timer)
(Set timer duration) as setTimerDuration
timeJudge --> setTimerDuration

note right of setTimerDuration: 60s / 120s

newpage
left to right direction

Spectator --> (View competition data)
Spectator --> (View bound data)
Spectator --> (View bound play)
note right of (View bound play): Spectator can see the development of a competition on air

Spectator --> (View bound results)
Spectator --> (View classifications)
Spectator --> (Download classifications)
Spectator --> (View weightin act)


newpage
left to right direction
Admin --> (Manage organizers)
Admin --> (Manage inscribers)
Admin --> (Manage clubs)
@enduml