@startuml

Organizer as Organizer
note top of Organizer
This is the competition organizer, tasks:
    sets number of bounds,
    sets classification methods,
    sets competition data such as date, location, etc
end note

Organizer -> (Set competition location)
Organizer -> (Set competition dates)
Organizer -> (Open/close inscriptions)
Organizer -> (Set competition type [master, senior])


Inscriber as Inscriber
note top of Inscriber
This actor is the one that inscribes
athletes in a competition form
end note


Time as Time
note top of Time
This actor interacts
when timers runs out
end note

CompetitionSecretary as CompetitionSecretary

Spectator as Spectator

' inscriber can share classifications, etc
' le puede llegar automáticamente la info


@enduml