@startuml
state LOGED_IN
state EDITED_CATEGORY
state SHOWED_CLUBS
state SHOWED_ORGANIZERS
state SHOWED_INSCRIBERS

state enterShowCategoriesCHC <<choice>>

state showCategories {
  [*] --> [*]
  note on link
    System shows:
    * edited categories

    For each showed category, 
    system allows to:
    * deleteCategory
    * editCategory

    Also, system allows to:
    * showClubs
    * showOrganizers
    * showInscribers
    * logout
  end note
}
state SHOWED_CATEGORIES

LOGED_IN --> enterShowCategoriesCHC
EDITED_CATEGORY --> enterShowCategoriesCHC
SHOWED_CLUBS --> enterShowCategoriesCHC
SHOWED_ORGANIZERS --> enterShowCategoriesCHC
SHOWED_INSCRIBERS --> enterShowCategoriesCHC

enterShowCategoriesCHC --> showCategories
note on link
  User requests to:
  * showCategories
end note
showCategories --> SHOWED_CATEGORIES

footer \n\n\n Especificación del caso de uso "showCategories"
@enduml
