@startuml
state SHOWED_CLUBS
state CHOSEN_CLUB

state deleteClub {
  [*] --> [*]
  note on link
    System allows to:
    * showClubs
  end note
}

state showClubs
state "SHOWED_CLUBS" as SHOWED_CLUBS_F

SHOWED_CLUBS --> CHOSEN_CLUB
note on link
  User chooses a club 
  at showed clubs
end note

CHOSEN_CLUB --> deleteClub
note on link
  User requests to:
  * deleteClub
end note

deleteClub --> showClubs
showClubs --> SHOWED_CLUBS_F

footer \n\n\n Especificación del caso de uso "deleteClub"
@enduml
