@startuml
state SHOWED_CLUBS
state CHOSEN_CLUB
state editClub {
  state createOrModifyCHC <<choice>>
  state " " as providedClub
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  [*] --> createOrModifyCHC
  createOrModifyCHC --> providedClub : There is a chosen club
  createOrModifyCHC --> createOrModifyCHC2 : The user is creating\na new club
  providedClub --> showedData
  note on link
    System shows:
    * Current club name
  end note
  showedData --> createOrModifyCHC2 : The user is modifying\na club
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * Name

    System allows to:
    * cancel
  end note
  pendingData --> showClubs
  note on link
    User requests to:
    * cancel
  end note
  showClubs --> SHOWED_CLUBS_F
  pendingData --> providedData 
  note on link
    User provides:
    * Name
  end note
  providedData --> [*]
  note on link
    System allows to:
    * showClubs
  end note
}
state EDITED_CLUB
state showClubs
state "SHOWED_CLUBS" as SHOWED_CLUBS_F

SHOWED_CLUBS --> CHOSEN_CLUB
note on link
  User chooses a club 
  at showed clubs
end note

CHOSEN_CLUB --> editClub
note on link
  User requests to:
  * editClub
end note

editClub --> EDITED_CLUB

footer \n\n\n Especificación del caso de uso "editClub"
@enduml
