@startuml
state SHOWED_ORGANIZERS
state CHOSEN_ORGANIZER

state deleteOrganizer {
  [*] --> [*]
  note on link
    System allows to:
    * showOrganizers
  end note
}

state showOrganizers
state "SHOWED_ORGANIZERS" as SHOWED_ORGANIZERS_F

SHOWED_ORGANIZERS --> CHOSEN_ORGANIZER
note on link
  User chooses a organizer 
  at showed organizers
end note

CHOSEN_ORGANIZER --> deleteOrganizer
note on link
  User requests to:
  * deleteOrganizer
end note

deleteOrganizer --> showOrganizers
showOrganizer --> SHOWED_ORGANIZER_F

footer \n\n\n Especificación del caso de uso "deleteOrganizer"
@enduml
