@startuml
state SHOWED_ORGANIZERS
state CHOSEN_ORGANIZER
state editOrganizer {
  state createOrModifyCHC <<choice>>
  state " " as providedOrganizer
  state " " as showedData
  state createOrModifyCHC2 <<choice>>
  state " " as pendingData
  state " " as providedData
  [*] --> createOrModifyCHC
  createOrModifyCHC --> providedOrganizer : There is a chosen organizer
  createOrModifyCHC --> createOrModifyCHC2 : The user is creating\na new organizer
  providedOrganizer --> showedData
  note on link
    System shows:
    * Current organizer name
  end note
  showedData --> createOrModifyCHC2 : The user is modifying\na organizer
  createOrModifyCHC2 --> pendingData
  note on link
    System requires:
    * Name

    System allows to:
    * cancel
  end note
  pendingData --> showOrganizers
  note on link
    User requests to:
    * cancel
  end note
  showOrganizers --> SHOWED_ORGANIZERS_F
  pendingData --> providedData 
  note on link
    User provides:
    * Name
  end note
  providedData --> [*]
  note on link
    System allows to:
    * showOrganizers
  end note
}
state EDITED_ORGANIZER
state showOrganizers
state "SHOWED_ORGANIZERS" as SHOWED_ORGANIZERS_F

SHOWED_ORGANIZERS --> CHOSEN_ORGANIZER
note on link
  User chooses a organizer 
  at showed organizers
end note

CHOSEN_ORGANIZER --> editOrganizer
note on link
  User requests to:
  * editOrganizer
end note

editOrganizer --> EDITED_ORGANIZER

footer \n\n\n Especificación del caso de uso "editOrganizer"
@enduml
