@startuml
state SHOWED_INSCRIBER
state deleteInscriber {
  state " " as pendingInscriber
  state " " as providedInscriber
  [*] --> pendingInscriber
  note on link
    System requires:
    * A specific inscriber
  end note
  pendingInscriber --> providedInscriber
  note on link
    User provides:
    * A specific inscriber
  end note
  providedInscriber --> [*]
  note on link
    System allows to:
    * showInscribers
  end note
}
state DELETED_INSCRIBER

SHOWED_INSCRIBER --> deleteInscriber
note on link
  User requests to:
  * deleteInscriber
end note

deleteInscriber --> DELETED_INSCRIBER

footer \n\n\n Especificación del caso de uso "deleteInscriber"
@enduml
