@startuml
state LOGED_IN
state SHOWED_LIVE_BATCH_IN_PLAY
state SHOWED_FINISHED_BATCHES
state SHOWED_BATCH_INSCRIPTIONS
state SHOWED_BATCH_WEIGHINS
state SHOWED_RESULTS

state enterCompetition <<choice>>


LOGED_IN  --> enterCompetition
SHOWED_LIVE_BATCH_IN_PLAY  --> enterCompetition
SHOWED_FINISHED_BATCHES  --> enterCompetition
SHOWED_BATCH_INSCRIPTIONS  --> enterCompetition
SHOWED_BATCH_WEIGHINS  --> enterCompetition
SHOWED_RESULTS  --> enterCompetition
enterCompetition --> showCompetitions
note on link
  User requests to:
  * showCompetitions
end note

state showCompetitions {
  [*] --> [*]
  note on link
    System shows:
    * available competitions

    System allows:
    * showCompetition
    * logout
  end note
}
state SHOWED_COMPETITIONS
showCompetitions --> SHOWED_COMPETITIONS

footer \n\n\n Especificación del caso de uso "showCompetitions"
@enduml
