@startuml
state SHOWED_LIVE_BATCH_IN_PLAY
state SHOWED_RESULTS
state SHOWED_COMPETITIONS
state SHOWED_FINISHED_BATCHES
state showFinishedBatches {
  state " " as availableCompetitions
  state " " as providedCompetition
  [*] --> availableCompetitions
  note on link
    System shows:
    * the finished batches

    System requires:
    * to select a finished batch

    System allows:
    * cancel
    * logout
  end note
  availableCompetitions --> [*]
  note on link
    User requests to:
    * logout
  end note
  availableCompetitions --> providedCompetition
  note on link
    User provides:
    * a finished batch
  end note
  providedCompetition --> [*]
  note on link
    System allows:
    * showLiveBatchInPlay
    * showResults
    * logout
  end note
}

SHOWED_LIVE_BATCH_IN_PLAY --> showFinishedBatches
note on link
  User requests to:
  * showFinishedBatches
end note
SHOWED_RESULTS --> showFinishedBatches
note on link
  User requests to:
  * showFinishedBatches
end note
SHOWED_COMPETITIONS --> showFinishedBatches
note on link
  User requests to:
  * showFinishedBatches
end note
showFinishedBatches --> SHOWED_FINISHED_BATCHES

footer \n\n\n Especificación del caso de uso "showFinishedBatches"
@enduml
