@startuml
state SHOWED_COMPETITION
state SHOWED_LIVE_BATCH_IN_PLAY
state showLiveBatchInPlay {
  [*] --> [*]
  note on link
    System shows:
    * live scores and weight changes 
    of the current batch

    System allows to:
    * showCompetition
    * logout
  end note
}

SHOWED_COMPETITION --> showLiveBatchInPlay
note on link
  User requests to:
  * showLiveBatchInPlay
end note
showLiveBatchInPlay --> SHOWED_LIVE_BATCH_IN_PLAY

footer \n\n\n Especificación del caso de uso "showLiveBatchInPlay"
@enduml
