@startuml
state SHOWED_COMPETITION
state showWeighins {
  state " " as pendingBatch
  state " " as providedBatch
  [*] --> pendingBatch
  note on link
    System requires:
    * A specific batch
  end note
  pendingBatch --> providedBatch
  note on link
    User provides:
    * A specific batch
  end note
  providedBatch --> [*]
  note on link
    System shows:
    * All the weighins in batch
    
    System allows to:
    * showCompetition
    * logout
  end note
}
state SHOWED_BATCH_WEIGHINS

SHOWED_COMPETITION --> showWeighins
note on link
  User requests to:
  * showWeighins
end note

showWeighins --> SHOWED_BATCH_WEIGHINS

footer \n\n\n Especificación del caso de uso "showWeighins"
@enduml
