@startuml

class Competition {
  - Integer id
  - String name
  - String location
  - String organizer
  - java.time.Period inscriptionPeriod
  - java.time.Period competitionPeriod
  - CompetitionType type
  - List<Batch> batches
}


class Batch {
  - Integer id
  - String name
  - LocalDate date
  - LocalDateTime weighinTime
  - LocalDateTime startTime
  - List<Plarform> platforms
  - CompetitionSecretary competitionSecretary
  - Marshall marshall
  - Timekeeper timeKeeper
}



class Platform {
  - Integer id
  - String name
  - List<Lifter> lifters
  - Gender gender
  - List<BarLoader> barLoaders
  - List<Judge> judges
  - List<Lifter> lifters
}



abstract class TechnicalOfficer <<mappedSuperclass>> {
  - Integer id
  - String name
}

class Judge {
  ---
  + judge()
}

class Marshall {
}

class CompetitionSecretary {
}

class Timekeeper {
}

class BarLoader {
}


class Lift {
   LiftStatus status
   Type type
   BarSet barset
   Countdown countdown
}

class Lifter {
  - Integer id
  - Integer lotNumber
}

class Club {
  - Integer id
  - String name
}


class Organizer {
  - Integer id
  - String name
}


class Inscriber {
  - Integer id
  - String name
}


enum Gender {
  MALE(M)
  FEMALE(F)
}

enum Type {
  SNATCH
  CLEAN_&_JERK
}

enum LiftStatus {
  PENDING
  VALID
  NULL
  REJECTED
}

enum Countdown {
  1_MINUTES(1)
  2_MINUTES(2)
}

enum Bar {
  FEMALE (15kg)
  MALE (20kg)
}

enum Plate {
  BIG_RED (25KG)
  BIG_BLUE (20KG)
  BIG_YELLOW (15KG)
  BIG_GREEN (10KG)
  BIG_WHITE (5)
  SMALL_RED (2.5KG)
  SMALL_BLUE (2KG)
  SMALL_YELLOW (1.5KG)
  SMALL_GREEN (1KG)
  SMALL_WHITE (0.5KG)
}

enum Collar {
  COLLAR(2.5KG)
}



class BarSet {
   - Bar bar
   - List<Collar> collars
   - List<Plate> plates
}

'
'Competition  *--> Batch
'BarSet *--> Bar
'BarSet *--> Collar
'BarSet *--> Plate
'
'TechnicalOfficer <|-- Judge
'TechnicalOfficer <|-- Marshall
'TechnicalOfficer <|-- CompetitionSecretary
'TechnicalOfficer <|-- Timekeeper
'TechnicalOfficer <|-- BarLoader
'Platform ..> Gender
'Platform ..> BarLoader
'Platform ..> Judge
'
'
'Batch *--> Platform
'Batch ..> Marshall
'Batch ..> Timekeeper
'Batch ..> CompetitionSecretary
'
Lift *--> LiftStatus
Lift *--> Type
Lift *--> Countdown
Lift o--> BarSet



@enduml