@startuml

Organizer as Organizer
note top of Organizer
This is the competition organizer, tasks:
    sets number of bounds,
    sets classification methods,
    sets competition data such as date, location, etc
end note


Inscriber as Inscriber
note top of Inscriber
This actor is the one that inscribes athletes in a competition form
end note


Time as Time
note top of Time
This actor interacts with timers
end note



' note right of Admin : This is an example.

'note right of (Use)
'A note can also
'be on several lines
'end note
'
'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)
@enduml