@startuml

node webServer
node dataBaseServer
component browser
component halteroCmsClient
component "webServer" <<Tomcat>> as webServerComponent

component halteroCmsService.war
component dbServer <<MySQL>>

folder views

folder controllers
folder daos
folder models

browser --> webServer : http
webServer *-d-> halteroCmsClient

webServer -r- dataBaseServer : jdbc
webServer *--> webServerComponent
webServerComponent .r.> halteroCmsService.war : uses
webServer *--> halteroCmsService.war

dataBaseServer *--> dbServer

browser ..> halteroCmsClient : renders
halteroCmsClient <.r. webServerComponent : uses
halteroCmsClient ..> views
halteroCmsService.war .r.> dbServer : uses

halteroCmsService.war ..> controllers
halteroCmsService.war ..> daos
halteroCmsService.war ..> models

@enduml
