@startuml

'''NOTA:
'''AÑADIR AQUÍ LOS DATOS DE CONEXIÓN, NO EN EL DIAGRAMA DE ANÁLISIS

node webServer
node dataBaseServer
component browser
component halteroCmsClient
component "webServer" <<Tomcat>> as webServerComponent

component halteroCmsService.war
component dbServer <<MySQL>>

file page.html

folder views

folder controllers
folder daos
folder models

browser --> webServer : http
webServer *-d-> halteroCmsClient
halteroCmsClient .l.> page.html

webServer -r- dataBaseServer : jdbc
webServer *--> webServerComponent
webServerComponent .r.> halteroCmsService.war : uses
webServer *--> halteroCmsService.war

dataBaseServer *--> dbServer

browser ..> page.html : renders
halteroCmsClient <.r. webServerComponent : uses
halteroCmsClient ..> views
halteroCmsService.war .r.> dbServer : uses

halteroCmsService.war ..> controllers
halteroCmsService.war ..> daos
halteroCmsService.war ..> models

@enduml
