@startuml

actor user as "Competition\nSecretary"

boundary WelcomeView
boundary LoginView
boundary CompetitionSecretaryView
control LoginController
control UsersDAO
entity CompetitionSecretary
database MySQL

user -> WelcomeView : start()
WelcomeView -> LoginView : new LoginView()
WelcomeView <- LoginView : LoginView view
user <- WelcomeView : LoginView view

user -> LoginView : login(username, password)
LoginView -> LoginController : login(username, password)
LoginController -> UsersDAO : findByUsernameAndPassword(username, password)

UsersDAO -> MySQL : SELECT * FROM users WHERE username = <username> AND password = <password>;
UsersDAO <- MySQL : found register

UsersDAO -> CompetitionSecretary : new CompetitionSecretary(name)
UsersDAO <- CompetitionSecretary : CompetitionSecretary competitionSecretary
LoginController <- UsersDAO : CompetitionSecretary competitionSecretary
LoginView <- LoginController : OK response
LoginView -> CompetitionSecretaryView : new CompetitionSecretaryView()
LoginView <- CompetitionSecretaryView : CompetitionSecretaryView view
user <- LoginView : CompetitionSecretaryView view

@enduml
