@startuml

actor user as "Competition\nSecretary"

boundary CompetitionSecretaryView
boundary ShowCompetitionsView
boundary CompetitionSecretaryEditBatchView
control ShowCompetitionsController
control CompetitionsDAO
entity Competition
database MySQL

user -> CompetitionSecretaryView : start()
CompetitionSecretaryView -> ShowCompetitionsView : new ShowCompetitionsView()
CompetitionSecretaryView <- ShowCompetitionsView : ShowCompetitionsView view
user <- CompetitionSecretaryView : ShowCompetitionsView view

user -> ShowCompetitionsView : showCompetitions()
ShowCompetitionsView -> ShowCompetitionsController : getCompetitions()
ShowCompetitionsController -> CompetitionsDAO : findAll()

CompetitionsDAO -> MySQL : SELECT * FROM competitions;
CompetitionsDAO <- MySQL : found registers

CompetitionsDAO -> Competition : Arrays.asList(competitionsArray)
CompetitionsDAO <- Competition : List<Competition> competitions
ShowCompetitionsController <- CompetitionsDAO : List<Competition> competitions
ShowCompetitionsView <- ShowCompetitionsController : List<Competition> competitions
ShowCompetitionsView -> CompetitionSecretaryEditBatchView : new CompetitionSecretaryEditBatchView()
ShowCompetitionsView <- CompetitionSecretaryEditBatchView : CompetitionSecretaryEditBatchView view
user <- ShowCompetitionsView : CompetitionSecretaryEditBatchView view

@enduml
