@startuml

actor user as "Competition\nSecretary"

boundary CompetitionSecretaryPlayView as "X-thymeleaf-view.html"
control CompetitionSecretaryPlayController as "YController.java"
control WeighinsDAO as "ZDAO.java"
entity Weighin as "ZEntity.java"
database MySQL

user -> CompetitionSecretaryPlayView : request through browser route
CompetitionSecretaryPlayView -> CompetitionSecretaryPlayController : controllerMethod(model, args)
CompetitionSecretaryPlayController -> WeighinsDAO : findByArgs(args) || save(entity)

WeighinsDAO -> MySQL : SQL query
WeighinsDAO <- MySQL : retrieved weighin tuples

WeighinsDAO -> Weighin : new ZEntity(<weighin tuple>)
WeighinsDAO <- Weighin : ZEntity builtZEntity
CompetitionSecretaryPlayController <- WeighinsDAO : ZEntity entity || List<ZEntity> ZEntities
CompetitionSecretaryPlayView <- CompetitionSecretaryPlayController : "x-thymeleaf-view"
user <- CompetitionSecretaryPlayView : rendered "x-thymeleaf-view" view

@enduml
