@startuml
state BATCH_MANAGEMENT
state BATCH_IN_PLAY
state initPlay {

  [*] --> [*]
  note on link
    System allows to:
    * editLiftValue
    * editWeightChange
    * showLifterCategory
    * startTimer
    * pauseTimer
    * resumeTimer
    * setDurationTimer
    * stopTimer

    ... if all weighins are performed
  end note

}

BATCH_MANAGEMENT --> initPlay
note on link
  User requests to:
  * initPlay
end note

initPlay --> BATCH_IN_PLAY

footer \n\n\n Especificación del caso de uso "initPlay"
@enduml