@startuml
state BATCH_IN_PLAY
state "BATCH_IN_PLAY" as BATCH_IN_PLAY_F
state editWeightChange {
  state " " as SHOWED_LIFTS_VALUE
  state " " as CHOSEN_LIFTER
  state " " as REQUIRED_DATA
  state " " as PROVIDED_DATA

  [*] --> SHOWED_LIFTS_VALUE
  note on link
    System shows:
    * lifters name
    * lifts type
    * lifts order
    * lifts weight changes

    System allows to:
    * choose a lifter, a lift type,
      a lift order and a weight change order
    * cancel
  end note
  
  SHOWED_LIFTS_VALUE --> CHOSEN_LIFTER
  note on link
    Competition Secretary
    chooses one of each:
    * a lifter
    * a lift type
    * a lift order
    * a weight change order
  end note

  SHOWED_LIFTS_VALUE -down-> BATCH_IN_PLAY_F
  note on link
    Competition Secretary
    requests to:
    * cancel
  end note

  CHOSEN_LIFTER --> REQUIRED_DATA
  note on link
    System requires:
    * lift weight change value

    System allows to:
    * provide required data
    * cancel
  end note

  REQUIRED_DATA -down---> BATCH_IN_PLAY_F
  note on link
    Competition Secretary
    requests to:
    * cancel
  end note

  REQUIRED_DATA --> PROVIDED_DATA
  note on link
    Competition Secretary
    provides:
    * lift weight change value
  end note

  PROVIDED_DATA --> [*]
  note on link
    System allows to:
    * editWeightChange
    * showLifterCategory
    * startTimer
    * pauseTimer
    * resumeTimer
    * setDurationTimer
    * stopTimer
  end note


  PROVIDED_DATA --> REQUIRED_DATA : Lower or equal to previous weight change\nOR higuer or equal to next weight change\nOR negative value\nOR non-numeric value
}

BATCH_IN_PLAY --> editWeightChange
note on link
  Competition Secretary
  requests to:
  * editWeightChange
end note

editWeightChange ---> BATCH_IN_PLAY_F

footer \n\n\n Especificación del caso de uso "editWeightChange"
@enduml
