@startuml

state "1_WebMap_Spectator" as launch
state "Logged as organization secretary" as login
login: <img:./images/2_organizationSecretaryMain.png>

[*] --> launch
note on link
  launch
end note

launch --> login
note on link
  login
end note

state organizationSecretaryChoice <<choice>>
login --> organizationSecretaryChoice


state " " as showCategories
showCategories: <img:./images/2_1_showCategories.png>
state " " as editCategories
editCategories: <img:./images/2_1_1_editCategories.png>

state " " as showClubs
showClubs: <img:./images/2_2_showClubs.png>
state " " as editClub
editClub: <img:./images/2_2_1_editClub.png>

state " " as showOrganizers
showOrganizers: <img:./images/2_4_showOrganizers.png>
state " " as editOrganizer
editOrganizer: <img:./images/2_4_1_editOrganizers.png>

state " " as showInscribers
showInscribers: <img:./images/2_3_showInscribers.png>
state " " as editInscriber
editInscriber: <img:./images/2_3_1_editInscriber.png>

organizationSecretaryChoice --> showCategories
note on link
  showCategories
end note

showCategories --> showCategories
note on link
  deleteCategory
end note

showCategories --> editCategories
note on link
  editCategory
end note

organizationSecretaryChoice --> showClubs
note on link
  showClubs
end note

showClubs --> showClubs
note on link
  deleteClub
end note

showClubs --> editClub
note on link
  editClub
end note


organizationSecretaryChoice --> showOrganizers
note on link
  showOrganizers
end note

showOrganizers --> showOrganizers
note on link
  deleteOrganizer
end note

showOrganizers --> editOrganizer
note on link
  editOrganizer
end note


organizationSecretaryChoice --> showInscribers
note on link
  showInscribers
end note

showInscribers --> showInscribers
note on link
  deleteInscriber
end note

showInscribers --> editInscriber
note on link
  editInscriber
end note


showCategories ---> organizationSecretaryChoice
showClubs --> organizationSecretaryChoice
showInscribers ---> organizationSecretaryChoice
showOrganizers --> organizationSecretaryChoice


editClub --> showClubs
note on link
  showClubs
end note


editCategories --> showCategories
note on link
  showCategories
end note


editOrganizer --> showOrganizers
note on link
  showOrganizers
end note

editInscriber --> showInscribers
note on link
  showInscribers
end note


@enduml