@startuml

state "...." as launch
state "Logged as organizator" as login
login: <img:./images/4_organizerMain.png>

[*] --> launch
note on link
  launch
end note

launch --> login
note on link
  login
end note

state " " as showCompetitions
showCompetitions: <img:./images/4_1_showCompetitions.png>

state " " as editCompetition
editCompetition: <img:./images/4_1_1_editCompetition.png>


login --> showCompetitions
note on link
  showCompetitions
end note

showCompetitions --> showCompetitions
note on link
  deleteCompetition
end note

showCompetitions --> editCompetition
note on link
  editCompetition
end note

editCompetition --> editCompetition
note on link
  showBatches
  deleteBatch
end note

state " " as editBatch
editBatch:  <img:./images/4_1_1_1_editBatch.png>

editCompetition --> editBatch
note on link
  editBatch
end note

editBatch --> editBatch
note on link
  assignLifterToBatch
  unassignLifterToBatch
end note

@enduml