@startuml
state "Competition pending\nto be edited" as PedingCompetition
state "Competition edited, pending\nto assign all the batches" as PedingAssignBatches
state "Competition edited with all\nthe batches assigned" as CompetitionEdited

state "Age categories pending\nto be edited" as PendingCategories
state "All the age categories edited" as CategoriesEdited

state MoreCategoriesToEditCHC <<choice>>

state "Pending new lifters to register" as PendingLiftersToRegister
state "Is the registration time still open?" as IsRegistrationOpenCHC <<choice>>
state "More lifters to register pending?" as MoreLiftersToRegisterCHC <<choice>>
state "A new lifter was registered" as NewLifterRegistered
state "Registration time is over" as RegistrationTimeOver
state "Is there any lifter registered?" as AnyLiftersRegisteredCHC <<choice>>
state "Competition order drawn" as CompetitionOrderDrawn
state "Pending new batches" as PendingNewBatch
state "A new category from a\ncertain batch started" as StartedNewBatchCategory
state "More batches pending?" as MoreCategoryBatchesCHC <<choice>>
state "Classification is open" as OpenClassification
state "Classification completed" as CompletedClassification
state "More batches from other categories pending?" as MoreBatchesCHC <<choice>>
state "All batches are completed" as CompletedBatches

[*] --> PedingCompetition : Creating a new\ncompetition
[*] --> PendingCategories : We prepare to create\nnew categories
PendingCategories --> CategoriesEdited : Editing the last\nage category
PedingCompetition --> PedingAssignBatches : Editing the competition\ndata
PedingAssignBatches --> CompetitionEdited : Assigning batches to\nthe competition
CompetitionEdited --> MoreCategoriesToEditCHC : Are there any categories\nleft to edit?
MoreCategoriesToEditCHC --> PendingLiftersToRegister : [All the categories\nwere edited]
MoreCategoriesToEditCHC --> PendingCategories : [Categories remain\nto be edited]
CategoriesEdited --> PendingLiftersToRegister : Opening inscriptions

PendingLiftersToRegister --> IsRegistrationOpenCHC : A new lifter tries\nto be registered
IsRegistrationOpenCHC --> RegistrationTimeOver : [Registration time\nran out]
IsRegistrationOpenCHC --> NewLifterRegistered : [The registration period\nis still open]
NewLifterRegistered --> MoreLiftersToRegisterCHC : Are there any lifters left\nto be registered?
MoreLiftersToRegisterCHC --> PendingLiftersToRegister : [Lifters remain to\nbe registered]
MoreLiftersToRegisterCHC --> RegistrationTimeOver : [All lifters are\nregistered]
PendingLiftersToRegister --> RegistrationTimeOver : Registration time\nran out
RegistrationTimeOver --> AnyLiftersRegisteredCHC : Does the competition have\nregistered lifters?
AnyLiftersRegisteredCHC --> CompetitionOrderDrawn : [Yes, so the draw\ntakes place]
AnyLiftersRegisteredCHC --> [*] : [No lifter has\nsigned up]
CompetitionOrderDrawn --> PendingNewBatch : The development of the\ncompetition begins

PendingNewBatch --> StartedNewBatchCategory : A new batch related to a\ncertain category starts
StartedNewBatchCategory --> MoreCategoryBatchesCHC : New batch related to certain\ncategory is completed

MoreCategoryBatchesCHC --> PendingNewBatch : [Some batches from the\nsame category have not\nbeen classified yet]
MoreCategoryBatchesCHC --> OpenClassification : [All batches from a the same\ncategory are completed]
OpenClassification --> CompletedClassification : Score is calculated and\nwinner is determined
CompletedClassification --> MoreBatchesCHC : Are there any categories\nleft to classify?
MoreBatchesCHC --> PendingNewBatch : [Yes, some categories have not\nbeen classified yet]
MoreBatchesCHC --> CompletedBatches : [No, all batches have been\nclassified]
CompletedBatches --> [*] : Competition is finished
@enduml
