@startuml

top to bottom direction

package views {
  boundary showCompetitionsView
  boundary showCompetitionView

  boundary showInscriptionsView
  boundary showFinishedBatchView
  boundary showBatchWeighinView
  boundary showLiveBatchInPlayView

  boundary loginView

  showCompetitionsView -- showCompetitionView
  showCompetitionView -- showInscriptionsView
  showCompetitionView -- showFinishedBatchView
  showCompetitionView -- showBatchWeighinView
  showCompetitionView -- showLiveBatchInPlayView


  boundary showCategoriesView
  boundary editCategoryView


  boundary showClubsView
  boundary editClubView


  boundary showOrganizersView
  boundary editOrganizerView

  boundary showInscribersView
  boundary editInscriberView


  boundary showInscribedLiftersView

  boundary editCompetitionView
  boundary editBatchView

  boundary showLiftView
  boundary timerView

  boundary welcomeView

  welcomeView -- showCompetitionsView

  boundary loginView

  welcomeView -- loginView

  boundary secretaryOrganizationView

  loginView -- secretaryOrganizationView

  secretaryOrganizationView -- showInscribersView
  secretaryOrganizationView -- showCategoriesView
  secretaryOrganizationView -- showOrganizersView
  secretaryOrganizationView -- showClubsView

  showClubsView -- editClubView
  showOrganizersView -- editOrganizerView
  showInscribersView -- editInscriberView
  showCategoriesView -- editCategoryView

  boundary editInscribedLifterView
  loginView -- showInscribedLiftersView
  showInscribedLiftersView -- editInscribedLifterView


  boundary inscriberView
  loginView -- inscriberView
  inscriberView -- showInscribedLiftersView

  boundary organizerView
  loginView -- organizerView
  organizerView -- showCompetitionsView
  showCompetitionsView -- editCompetitionView

  boundary competitionSecretaryView
  boundary competitionSecretaryEditBatchView
  boundary competitionSecretaryPlayView

  loginView -- competitionSecretaryView
  competitionSecretaryView -- showCompetitionsView



  showCompetitionsView -- competitionSecretaryEditBatchView
  competitionSecretaryEditBatchView -- competitionSecretaryPlayView

  showLiveBatchInPlayView -- showLiftView
  showLiveBatchInPlayView -- timerView

  showCompetitionView -- editBatchView
}

@enduml