@startuml

top to bottom direction

package views {
  boundary showCompetitionsView
  boundary showCompetitionView

  boundary showInscriptionsView
  boundary showFinishedBatchView
  boundary showBatchWeighinView
  boundary showLiveBatchInPlayView

  boundary loginView

  showCompetitionsView -- showCompetitionView
  showCompetitionView -- showInscriptionsView
  showCompetitionView -- showFinishedBatchView
  showCompetitionView -- showBatchWeighinView
  showCompetitionView -- showLiveBatchInPlayView


  boundary showCategoriesView
  boundary editCategoryView


  boundary showClubsView
  boundary editClubView


  boundary showOrganizersView
  boundary editOrganizerView

  boundary showInscribersView
  boundary editInscriberView


  boundary showInscribedLiftersView

  boundary editCompetitionView
  note top of editCompetitionView: ¡raro! indicaría la opibilidad de llegar aquí solo desde organizer

  boundary editBatchView

  boundary showLiftView
  boundary timerView

  boundary welcomeView

  welcomeView -- showCompetitionsView

  boundary loginView

  welcomeView -- loginView

  boundary secretaryOrganizationView

  loginView -- secretaryOrganizationView

  secretaryOrganizationView -- showInscribersView
  secretaryOrganizationView -- showCategoriesView
  secretaryOrganizationView -- showOrganizersView
  secretaryOrganizationView -- showClubsView

  showClubsView -- editClubView
  showOrganizersView -- editOrganizerView
  showInscribersView -- editInscriberView
  showCategoriesView -- editCategoryView

  boundary editInscribedLifterView
  loginView -- showInscribedLiftersView
  showInscribedLiftersView -- editInscribedLifterView


  boundary inscriberView
  loginView -- inscriberView
  inscriberView -- showInscribedLiftersView

  boundary organizerView
  loginView -- organizerView
  organizerView -- showCompetitionsView
  showCompetitionsView -- editCompetitionView

  boundary competitionSecretaryView
  boundary competitionSecretaryEditBatchView
  boundary competitionSecretaryPlayView

  loginView -- competitionSecretaryView
  competitionSecretaryView -- showCompetitionsView



  showCompetitionsView -- competitionSecretaryEditBatchView
  competitionSecretaryEditBatchView -- competitionSecretaryPlayView

  showLiveBatchInPlayView -- showLiftView
  showLiveBatchInPlayView -- timerView

  showCompetitionView -- editBatchView
}

package controllers {

  package competitionPlay {
      control showBatchesController
      control editBatchController
      control deleteBatchController

        control assignLifterToBatchController

      control showLifterCategoryController
      control editLiftStatusController
      control editLiftValueController
      control editLiftWeightChangeController
      control createActController
      control downloadActController
      control introduceWeighinDataController
      control initPlayController
      control finishPlayController


            control startController
            control pauseController
            control resumeController
            control setDurationController
            control stopController

  }

  package inscriptions {
    control openInscriptionsPeriodController
    control showInscriptionsController
    control closeInscriptionsController
    control deleteCompetitionController
    control editCompetitionController
    control showCompetitionsController
    control drawLiftersController
    control inscribeLifterController
    control showInscribedLiftersController
  }



  package organizational {
    control showClubsController
    control editClubController
    control deleteClubController
    control showOrganizersController
    control editOrganizerController
    control deleteOrganizerController
    control showInscribersController
    control deleteInscriberController
    control editInscriberController
    control deleteCategoryController
    control editCategoryController
    control showCategoriesController
    control editBodyWeightCategoryController
    control deleteBodyWeightCategoryController
  }


package monitoring {
  control showCompetitionController
  control showBatchInscriptionsController
  control showBatchWeighinsController
  control showFinishedBatchesController
  control showLiveBatchInPlayController
  control showResultsController
  control downloadResultsController
  control showCompetitionsController
  control createClassificationsController
  control downloadClassificationsController
  control showClassificationsController

    control launchController
    control loginController
    control logoutController
}

}

package models {
    entity ageRange
    entity barSet
    entity batch
    entity bodyWeightRange
    entity category
    entity club
    entity competition
    entity competitionSecretary
    entity inscription
    entity judge
    entity lift
    entity lifter
    entity marshall
    entity platform
    entity technicalOfficer
    entity timekeeper
    entity weighin
}

views ..> controllers
views ..> models
controllers ..> models

header NOTA !!!!!! Faltaría añadir las entidades correspondientes a las clases que faltan en el modelo\nTambién faltaría dividir las entidades en paquetes más pequeños si hiciese falta\n(No dividir hasta que estén todas las entidades aquí puestas)
@enduml