@startuml
state SHOWED_CATEGORIES
state CHOSEN_CATEGORY

state deleteCategory {
  [*] --> [*]
  note on link
    System allows to:
    * showCategories
  end note
}

state showCategories
state "SHOWED_CATEGORIES" as SHOWED_CATEGORIES_F

SHOWED_CATEGORIES --> CHOSEN_CATEGORY
note on link
  User chooses a category 
  at showed categories
end note

CHOSEN_CATEGORY --> deleteCategory
note on link
  User requests to:
  * deleteCategory
end note

deleteCategory --> showCategories
showCategories --> SHOWED_CATEGORIES_F

footer \n\n\n Especificación del caso de uso "deleteCategory"
@enduml
