@startuml
state LOGED_IN
state EDITED_ORGANIZERS
state SHOWED_CATEGORIES
state SHOWED_CLUBS
state SHOWED_INSCRIBERS

state enterShowOrganizersCHC <<choice>>

state showOrganizers {
  [*] --> [*]
  note on link
    System shows:
    * edited organizers

    For each showed organizer, 
    system allows to:
    * deleteOrganizer
    * editOrganizer

    Also, system allows to:
    * showCategories
    * showClubs
    * showInscribers
    * logout
  end note
}
state SHOWED_ORGANIZERS

LOGED_IN --> enterShowOrganizersCHC
EDITED_ORGANIZERS --> enterShowOrganizersCHC
SHOWED_CATEGORIES --> enterShowOrganizersCHC
SHOWED_CLUBS --> enterShowOrganizersCHC
SHOWED_INSCRIBERS --> enterShowOrganizersCHC

enterShowOrganizersCHC --> showOrganizers
note on link
  User requests to:
  * showOrganizers
end note
showOrganizers --> SHOWED_ORGANIZERS

footer \n\n\n Especificación del caso de uso "showOrganizers"
@enduml
